### ISSUE TITLE
Adapter is terminating

### ISSUE THREAD

**Issue by magnus2501** [iobroker-community-adapters/ioBroker.yeelight-2#1]
Hi, I am fairly new to the whole iobroker world, but am slowly making progress. I am however lost with the yeelight adapter as it started out working quite well, but is now stopping either after a while or even directly when being started. The error messages in the log are quite extensive, but unfortunately don't mean a lot to me. Any help or suggestions would be appreciated. Log attached. Thanks
[yeelight adapter log.log](https://github.com/MeisterTR/ioBroker.yeelight-2/files/2165539/yeelight.adapter.log.log)

**Comment by MeisterTR** [comment]
Can you also upload a pic of the Config and the objects in. Yeelight.0.xxx.info.

**Comment by magnus2501** [comment]
Is this the right information? 

![config](https://user-images.githubusercontent.com/40852401/42331889-e3cf787a-8076-11e8-8f6a-0d7fb9799fc4.JPG)
![objects](https://user-images.githubusercontent.com/40852401/42331891-e3ed0ed0-8076-11e8-820e-83cdf7d97a75.JPG)

**Comment by MeisterTR** [comment]
delete the folder yeelight-2 from objects and after that, restart the adapter. then you schould only see 2 devices and not 4.

**Comment by magnus2501** [comment]
I tried that, but it actually let to every device being 2 or 3 times listed. I know try to delete / reinstall the whole thing once more and check if only 2 devices are shown. Will post back with result or new problems. :-)

**Comment by magnus2501** [comment]
I just deleted everything, deinstalled the adapter, rebooted the raspberry and after it was up again installed the adapter with version 0.3.5. Searched for me lamps, found both, renamed them and saved.
In Objects I get right away 4 again, each is listed twice (see picture below). Not sure if this will now work more stable or stop working again, for now there are no error messages and I will monitor the situation. Is it a problem with the 2 actual devices being listed twice each?

![grafik](https://user-images.githubusercontent.com/40852401/42368427-4a7601ee-8107-11e8-91ca-535f3802c105.png)

**Comment by MeisterTR** [comment]
so i testet it. you cant use space in your devicename.

**Comment by MeisterTR** [comment]
fixed in 0.3.6 (after update, please delete all yeelight Objects manuelly)

**Comment by magnus2501** [comment]
Great, thanks. Will test it tomorrow.
