### ISSUE TITLE
Adapter schaltet sich von alleine ab

### ISSUE THREAD

**Issue by thurbo** [iobroker-community-adapters/ioBroker.yeelight-2#102]
Der Adapter schaltet sich von alleine ab.
Muss mehrfach am Tag (8-15 mal) manuell wieder starten.

Bitte bald ein Update, hab 6 Lampen dran am Adapter.

**Comment by MeisterTR** [comment]
fehlermeldungen im log? von alleine kann er sich nicht abschalten
