### ISSUE TITLE
has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by crunchip77** [iobroker-community-adapters/ioBroker.yeelight-2#107]
Habe gerade das Update auf v1.1.0 gemacht, jedoch ist folgendes noch nicht behoben.
`

yeelight-2.0 | 2021-07-27 17:50:47.197 | info | (7772) State value to set for "yeelight-2.0.Esstisch.control.bg_ct" has to be type "number" but received type "string"
-- | -- | -- | --
yeelight-2.0 | 2021-07-27 17:50:47.161 | info | (7772) State value to set for "yeelight-2.0.Esstisch.control.bg_sat" has to be type "number" but received type "string"
yeelight-2.0 | 2021-07-27 17:50:47.160 | info | (7772) State value to set for "yeelight-2.0.Esstisch.control.bg_hue" has to be type "number" but received type "string"
yeelight-2.0 | 2021-07-27 17:50:47.158 | info | (7772) State value to set for "yeelight-2.0.Esstisch.control.bg_bright" has to be type "number" but received type "string"
yeelight-2.0 | 2021-07-27 17:50:44.800 | info | (7772) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.yeelight-2, node: v14.17.2, js-controller: 3.3.15

`

**Comment by jlssmt** [comment]
ich habe das problem nicht (mehr).
wann tritt es bei dir auf?

**Comment by crunchip77** [comment]
das war nach einem Neustart der Instanz, habe soeben erneut die Instanz neu gestartet, diesmal ohne Meldungen.

**Comment by MeisterTR** [comment]
fixed in 1.1.1

**Comment by jlssmt** [comment]
@MeisterTR 
i didnt fix it. i don't even get the problem...

**Comment by TDCroPower** [comment]
still there, @MeisterTR please reopen...

`
yeelight-2.0 | 2021-10-12 21:34:32.360 | info | State value to set for "yeelight-2.0.Yeelight_Meteorit.control.bg_ct" has to be type "number" but received type "string"
-- | -- | -- | --
yeelight-2.0 | 2021-10-12 21:34:32.353 | info | State value to set for "yeelight-2.0.Yeelight_Meteorit.control.bg_sat" has to be type "number" but received type "string"
yeelight-2.0 | 2021-10-12 21:34:32.352 | info | State value to set for "yeelight-2.0.Yeelight_Meteorit.control.bg_hue" has to be type "number" but received type "string"
yeelight-2.0 | 2021-10-12 21:34:32.350 | info | State value to set for "yeelight-2.0.Yeelight_Meteorit.control.bg_bright" has to be type "number" but received type "string"
`

**Comment by jlssmt** [comment]
@TDCroPower 
When exactly does the info message appear?
Maybe it is also because of your script? Are you maybe passing a string instead of a number? 
I'm not receiving the message anymore.
