### ISSUE TITLE
SyntaxError: Unexpected token { in JSON at position 44

### ISSUE THREAD

**Issue by gehrausundspiel** [iobroker-community-adapters/ioBroker.yeelight-2#11]
hello I get following error:

  syntaxError: Unexpected token { in JSON at position 44

The Position number is not always the same.
what is this?

update to 0.4.0

**Comment by MeisterTR** [comment]
therefor i need more informations. please set the adapter on debug an post the log. also you can update from git, there should the error fixed..

**Comment by gehrausundspiel** [comment]
Hallo Meister sprichst du deutsch? Do you speak german?

I Update the Adapter in Iobroker of?

Ich habe im Iobroker den Adapter 4.0 erneut installiert. Leider hat dies nichts verändert.

Log mache ich später

**Comment by gehrausundspiel** [comment]
Oder wie Update ich von Github?

**Comment by MeisterTR** [comment]
![2018-09-26_22h08_05](https://user-images.githubusercontent.com/6328382/46106359-be9f2e80-c1d8-11e8-83e2-ecca7d4bdaca.png)

da und dann bei url die git url eingeben, oder bis morgen früh warten und die 0.4.1 installieren

**Comment by gehrausundspiel** [comment]
Danke schön. mit 0.4.1 funktioniert es...
