### ISSUE TITLE
unhandled promise rejection: _joi2.default.validate is not a function

### ISSUE THREAD

**Issue by Diginix** [iobroker-community-adapters/ioBroker.yeelight-2#111]
version 1.1.1
JS-Controller 3.3.15
nodejs 2.12.4

> 2021-08-03 23:25:03.206  - info: yeelight-2.0 (219317) starting. Version 1.1.1 in /opt/iobroker/node_modules/iobroker.yeelight-2, node: v12.22.4, js-controller: 3.3.15
> 2021-08-03 23:25:05.274  - error: yeelight-2.0 (219317) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
> 2021-08-03 23:25:05.274  - error: yeelight-2.0 (219317) unhandled promise rejection: _joi2.default.validate is not a function
> 2021-08-03 23:25:05.275  - error: yeelight-2.0 (219317) TypeError: _joi2.default.validate is not a function
>     at /opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:216:23
>     at new Promise (<anonymous>)
>     at Yeelight.sendRequest (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:211:14)
>     at Yeelight.getValues (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:353:19)
>     at YeelightSearch.<anonymous> (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:475:15)
>     at YeelightSearch.emit (events.js:314:20)
>     at YeelightSearch.addInitLights (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/index.js:115:12)
>     at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:467:74)
>     at listOnTimeout (internal/timers.js:554:17)
>     at processTimers (internal/timers.js:497:7)
> 2021-08-03 23:25:05.276  - error: yeelight-2.0 (219317) _joi2.default.validate is not a function
> 2021-08-03 23:25:05.280  - info: yeelight-2.0 (219317) cleaned everything up...
> 2021-08-03 23:25:05.280  - info: yeelight-2.0 (219317) terminating
> 2021-08-03 23:25:05.281  - warn: yeelight-2.0 (219317) Terminated (UNCAUGHT_EXCEPTION): Without reason

**Comment by crunchip77** [comment]
das gleiche bei mir
`


yeelight-2.0 | 2021-08-04 11:01:28.166 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
yeelight-2.0 | 2021-08-04 11:01:28.165 | info | terminating
yeelight-2.0 | 2021-08-04 11:01:28.164 | info | cleaned everything up...
yeelight-2.0 | 2021-08-04 11:01:28.153 | error | _joi2.default.validate is not a function
yeelight-2.0 | 2021-08-04 11:01:28.152 | error | TypeError: _joi2.default.validate is not a function at /opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:216:23 at new Promise (<anonymous>) at Yeelight.sendRequest (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:211:14) at Yeelight.getValues (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:353:19) at YeelightSearch.<anonymous> (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:475:15) at YeelightSearch.emit (events.js:375:28) at YeelightSearch.addInitLights (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/index.js:115:12) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:467:74) at listOnTimeout (internal/timers.js:557:17) at processTimers (internal/timers.js:500:7)
yeelight-2.0 | 2021-08-04 11:01:28.151 | error | unhandled promise rejection: _joi2.default.validate is not a function
yeelight-2.0 | 2021-08-04 11:01:28.149 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
yeelight-2.0 | 2021-08-04 11:01:25.829 | info | starting. Version 1.1.1 in /opt/iobroker/node_modules/iobroker.yeelight-2, node: v14.17.2, js-controller: 3.3.15
yeelight-2.0 | 2021-08-04 11:00:50.519 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
yeelight-2.0 | 2021-08-04 11:00:50.517 | info | terminating
yeelight-2.0 | 2021-08-04 11:00:50.515 | info | cleaned everything up...
yeelight-2.0 | 2021-08-04 11:00:50.441 | error | _joi2.default.validate is not a function
yeelight-2.0 | 2021-08-04 11:00:50.437 | error | TypeError: _joi2.default.validate is not a function at /opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:216:23 at new Promise (<anonymous>) at Yeelight.sendRequest (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:211:14) at Yeelight.getValues (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:353:19) at YeelightSearch.<anonymous> (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:475:15) at YeelightSearch.emit (events.js:375:28) at YeelightSearch.addInitLights (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/index.js:115:12) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:467:74) at listOnTimeout (internal/timers.js:557:17) at processTimers (internal/timers.js:500:7)
yeelight-2.0 | 2021-08-04 11:00:50.432 | error | unhandled promise rejection: _joi2.default.validate is not a function
yeelight-2.0 | 2021-08-04 11:00:50.427 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
yeelight-2.0 | 2021-08-04 11:00:48.086 | info | starting. Version 1.1.1 in /opt/iobroker/node_modules/iobroker.yeelight-2, node: v14.17.2, js-controller: 3.3.15

`

**Comment by Ilovegym66** [comment]
hier gleicher Fehler, bin wieder auf 1.1.0 zurueck, die laeuft durch, bis auf die bekannten Issues, die mit 1.1.1 gefixt sind

**Comment by MarcelMertens** [comment]
Same here

**Comment by tobasium** [comment]
Gleiches Problem ebenfalls zurück auf 1.1.0

**Comment by MeisterTR** [comment]
bitte noch auf der 1.1.0 bleiben

**Comment by MeisterTR** [comment]
fixed in 1.1.2
