### ISSUE TITLE
Adapter hängt sich auf und startet immer wieder neu

### ISSUE THREAD

**Issue by Typ1er** [iobroker-community-adapters/ioBroker.yeelight-2#112]
nutze Version 1.1.1 Lampen habe ich zwei, wenn ich beide Lampen entferne läuft alles, mit einer älteren Version 1.0.3 
<img width="1812" alt="Bildschirmfoto 2021-08-05 um 10 48 55" src="https://user-images.githubusercontent.com/39628986/128321536-e56e202a-7da0-4c19-ae6e-dc432efcaa09.png">
habe die Probleme nicht.

st.iobroker | 2021-08-05 10:44:55.504 | error | instance system.adapter.yeelight-2.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
yeelight-2.0 | 2021-08-05 10:44:55.187 | error | _joi2.default.validate is not a function
yeelight-2.0 | 2021-08-05 10:44:55.186 | error | TypeError: _joi2.default.validate is not a function at /opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:216:23 at new Promise (<anonymous>) at Yeelight.sendRequest (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:211:14) at Yeelight.getValues (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:353:19) at YeelightSearch.<anonymous> (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:475:15) at YeelightSearch.emit (events.js:314:20) at YeelightSearch.addInitLights (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/index.js:115:12) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:467:74) at listOnTimeout (internal/timers.js:554:17) at processTimers (internal/timers.js:497:7)
yeelight-2.0 | 2021-08-05 10:44:55.185 | error | unhandled promise rejection: _joi2.default.validate is not a function
yeelight-2.0 | 2021-08-05 10:44:55.185 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
yeelight-2.0 | 2021-08-05 10:44:54.931 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
yeelight-2.0 | 2021-08-05 10:44:54.930 | info | terminating
yeelight-2.0 | 2021-08-05 10:44:54.929 | info | cleaned everything up...
yeelight-2.0 | 2021-08-05 10:44:54.896 | error | _joi2.default.validate is not a function
yeelight-2.0 | 2021-08-05 10:44:54.895 | error | TypeError: _joi2.default.validate is not a function at /opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:216:23 at new Promise (<anonymous>) at Yeelight.sendRequest (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:211:14) at Yeelight.getValues (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:353:19) at YeelightSearch.<anonymous> (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:475:15) at YeelightSearch.emit (events.js:314:20) at YeelightSearch.addInitLights (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/index.js:115:12) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:467:74) at listOnTimeout (internal/timers.js:554:17) at processTimers (internal/timers.js:497:7)
yeelight-2.0 | 2021-08-05 10:44:54.893 | error | unhandled promise rejection: _joi2.default.validate is not a function
yeelight-2.0 | 2021-08-05 10:44:54.892 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
yeelight-2.0 | 2021-08-05 10:44:52.810 | info | starting. Version 1.1.1 in /opt/iobroker/node_modules/iobroker.yeelight-2, node: v12.22.2, js-controller: 3.3.14
host.iobroker | 2021-08-05 10:44:51.556 | info | instance system.adapter.yeelight-2.0 started with pid 9777
host.iobroker | 2021-08-05 10:44:21.518 | info | Restart adapter system.adapter.yeelight-2.0 because enabled

**Comment by MeisterTR** [comment]
#111
