### ISSUE TITLE
Please add description to state

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.yeelight-2#12]
https://github.com/MeisterTR/ioBroker.yeelight-2/blob/master/main.js#L1307

What the mode is that? RGB/Temperature? RGB/HUE? Or Dim/Color? .....

And may be change the role, else it cannot be separated from power with the same role.

**Comment by MeisterTR** [comment]
color mode is the indecator for color/tempreture. i will add a disc. in next version. witch role is best for it?

**Comment by GermanBluefox** [comment]
switch.mode.color

MeisterTR <notifications@github.com> schrieb am Mi., 17. Okt. 2018, 19:39:

**Comment by MeisterTR** [comment]
done
