### ISSUE TITLE
Error-Messages in Logfile

### ISSUE THREAD

**Issue by KL-AU-S** [iobroker-community-adapters/ioBroker.yeelight-2#17]
I receive sporadically the following error-messages wtih yellight-2.1 Version 0.9.4:

yeelight-2.1	2018-11-19 17:13:11.618	info	cleaned everything up...
yeelight-2.1	2018-11-19 17:13:11.616	error	at TCP.onread (net.js:601:20)
yeelight-2.1	2018-11-19 17:13:11.616	error	at Socket.Readable.push (_stream_readable.js:208:10)
yeelight-2.1	2018-11-19 17:13:11.616	error	at readableAddChunk (_stream_readable.js:250:11)
yeelight-2.1	2018-11-19 17:13:11.616	error	at addChunk (_stream_readable.js:263:12)
yeelight-2.1	2018-11-19 17:13:11.616	error	at Socket.emit (events.js:211:7)
yeelight-2.1	2018-11-19 17:13:11.616	error	at emitOne (events.js:116:13)
yeelight-2.1	2018-11-19 17:13:11.616	error	at Yeelight.formatResponse (C:\ioBroker\node_modules\iobroker.yeelight-2\node_modules\yeelight-wifi\build\Yeelight.js:288:28)
yeelight-2.1	2018-11-19 17:13:11.616	error	ReferenceError: id is not defined
yeelight-2.1	2018-11-19 17:13:11.615	error	uncaught exception: id is not defined 

If you need further Trace please let me know.
Kind regards
Klaus

**Comment by MeisterTR** [comment]
after reinstall it should be fixed
