### ISSUE TITLE
Power on when rgb change

### ISSUE THREAD

**Issue by PierreKr** [iobroker-community-adapters/ioBroker.yeelight-2#2]
If the yeelight color is powerd off and I change the color, the yeelight power on, but in io.broker the yeelight "power" attr. stays on false.

Please check.

Thank you :)

Pierre

**Comment by MeisterTR** [comment]
which version?

**Comment by PierreKr** [comment]
0.3.6

**Comment by MeisterTR** [comment]
fixed on git
