### ISSUE TITLE
yeelight 650 bg_rgb not adjustable

### ISSUE THREAD

**Issue by jayfizzle** [iobroker-community-adapters/ioBroker.yeelight-2#21]
Hi,

first of all I wann thank you for thins amazing Adapter for iobroker, it works very good with the most lamps.
I have 1 problem with my yeelight 650. I can't change the bg_rgb (see attachment). The value is adjustable but has no effect. When I change the color with my yeelight app, the values in iobroker change too, when i type in the value in "bg_rgb" it does not have any effect, even I don't get an error (log=debug). 
Has somebody else the same problem? Or should i change the color in a special order?

regards
J

**Comment by MeisterTR** [comment]
can you send an debug log with changeing the value

**Comment by jayfizzle** [comment]
Hi, ok here is the log and before maybe some useful information:

When I change the value of bg_rgb via iobroker objects, I get the following log debug message:
- SEND STATE: id:0x0000000005e873f4, state: bg_rgb, value: #2aff37

when I change the color via the yeelight app, the log shows something like that:
- NOTIFY MESSAGE: from: 0x0000000005e873f4, message: {"method":"props","params":{"bg_rgb":16730378,"bg_hue":15,"bg_sat":96}}

the value of "bg_rgb" is not a hex Format, could this be the error?
the rgb value in the yeelight stripe object can be changed!

here is a part of the error log:
("ceiling4-" is the ceiling which has the bg_color issues.)
yeelight-2.0	2018-11-25 19:38:27.321	debug	DEVICE FOUND IN CONFIG: {"name":"ceiling4-0x0000000000000000","ip":"192.168.X.X","port":"55443","smart_name":"Wohnzimmerlampe","type":"ceiling4","id":"0x0000000005e873f4"}
yeelight-2.0	2018-11-25 19:38:27.319	debug	RESPONSE MESSAGE: from: 0x0000000005e873f4, id: 13, result:[on,100,,2,4000]}
yeelight-2.0	2018-11-25 19:38:17.999	debug	SEND STATE: id:0x0000000005e873f4, state: bg_rgb, value: #acffc3
yeelight-2.0	2018-11-25 19:38:10.158	debug	DEVICE FOUND IN CONFIG: {"name":"ceiling1-0x0000000000000000","ip":"192.168.X.X","port":"55443","smart_name":"Kuechenlampe","type":"ceiling1","id":"0x0000000005e27aa0"}
yeelight-2.0	2018-11-25 19:38:10.157	debug	RESPONSE MESSAGE: from: 0x0000000005e27aa0, id: 16, result:[on,1,,2,2700]}
yeelight-2.0	2018-11-25 19:37:57.279	debug	DEVICE FOUND SET NOTIFY STATE: {"name":"ceiling4-0x0000000000000000","ip":"192.168.X.X","port":"55443","smart_name":"Wohnzimmerlampe","type":"ceiling4","id":"0x0000000005e873f4"}
yeelight-2.0	2018-11-25 19:37:57.279	debug	NOTIFY MESSAGE: from: 0x0000000005e873f4, message: {"method":"props","params":{"bg_rgb":12123931,"bg_hue":79,"bg_sat":89}}
yeelight-2.0	2018-11-25 19:37:55.457	debug	DEVICE FOUND SET NOTIFY STATE: {"name":"ceiling4-0x0000000000000000","ip":"192.168.X.X","port":"55443","smart_name":"Wohnzimmerlampe","type":"ceiling4","id":"0x0000000005e873f4"}
yeelight-2.0	2018-11-25 19:37:55.456	debug	NOTIFY MESSAGE: from: 0x0000000005e873f4, message: {"method":"props","params":{"bg_rgb":65536,"bg_hue":0,"bg_sat":100}}
yeelight-2.0	2018-11-25 19:37:47.005	debug	DEVICE FOUND IN CONFIG: {"name":"ceiling4-0x0000000000000000","ip":"192.168.X.X","port":"55443","smart_name":"Wohnzimmerlampe","type":"ceiling4","id":"0x0000000005e873f4"}
yeelight-2.0	2018-11-25 19:37:47.004	debug	RESPONSE MESSAGE: from: 0x0000000005e873f4, id: 12, result:[on,100,,2,4000]}
yeelight-2.0	2018-11-25 19:37:16.985	debug	DEVICE FOUND IN CONFIG: {"name":"ceiling4-0x0000000000000000","ip":"192.168.X.X","port":"55443","smart_name":"Wohnzimmerlampe","type":"ceiling4","id":"0x0000000005e873f4"}
yeelight-2.0	2018-11-25 19:37:16.983	debug	RESPONSE MESSAGE: from: 0x0000000005e873f4, id: 11, result:[on,100,,2,4000]}

if you need further information, just ask.
thanks

**Comment by MeisterTR** [comment]
can you try this installation in Terminal
``` npm install https://github.com/MeisterTR/ioBroker.yeelight-2/tarball/add-yeelight-wifi --production --save```

**Comment by jayfizzle** [comment]
installed this version without errors, but still no effect when changing value of bg_rgb.

changing bg_rgb value from #34ff1e to #cc0000, i receive this log:

DEVICE FOUND IN CONFIG: {"id":"ceiling4-0x000000000XXXXXXX"","name":"ceiling4-0x000000000XXXXXXX","ip":"192.168.X.X","port":"55443","smart_name":"Wohnzimmerlampe","type":"ceiling4"}
yeelight-2.0	2018-11-30 20:42:24.173	debug	RESPONSE MESSAGE: from: ceiling4-0x000000000XXXXXXX", id: 6, result:[on,100,,2,4000]}
yeelight-2.0	2018-11-30 20:42:22.981	debug	SEND STATE: id:ceiling4-0x000000000XXXXXXX", state: bg_rgb, value: #cc0000

**Comment by jayfizzle** [comment]
sorry, after deinstalling the adapter and installing it again i think its working. I will test it more extensive the next days, but i think its working now. thanks

**Comment by MeisterTR** [comment]
so i think its work now?

**Comment by jayfizzle** [comment]
Yes, but i have now some other problems with the connection (sometimes the yeelight lose Connection to iobroker) and with the status „indicator.connection“ which switches from false to true or true to false when the power supply is disabled (by wall switch (Hardware)). Should i open a new issue with a Snapshot of my log?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MeisterTR** [comment]
that sounds right, if the power turned off the indecator should switch to false after a frew seconst (120)

**Comment by jayfizzle** [comment]
can be closed, opened another issue. maybe somebody can help me
