### ISSUE TITLE
Version 0.9.5 does not reconnect to bedside lamp

### ISSUE THREAD

**Issue by algar42** [iobroker-community-adapters/ioBroker.yeelight-2#22]
After upgrade to 0.9.5 I noticed that adapter does not reconnect to lamp after connection lost (e.g. wifi re-connection). Version 0.4.1 worked fine. 
I'm currently using a script to re-enable adapter when info.connect drops to false, but wonder if it is something that can be updated in adapter itself. 

thx.

**Comment by MeisterTR** [comment]
i tested it an its all ok, please try this installation in terminal
``` npm install https://github.com/MeisterTR/ioBroker.yeelight-2/tarball/add-yeelight-wifi --production --save```

**Comment by algar42** [comment]
Will try. Thank you!

**Comment by MeisterTR** [comment]
so i think its work now?

**Comment by algar42** [comment]
Still testing. It looks like nothing changed, but I can't find the root of the problem. 
Last time adapter switched connection status to false after this in my log:
![image](https://user-images.githubusercontent.com/40002726/49716118-c9a81d80-fc63-11e8-8700-7cfa58a558b9.png)
It looks like it is something connected with internet connection, but adapter works fine if I just unplug internet cable from router. Also everything is fine if I switch wifi off and and on.. 
Currently I confused.... :)

**Comment by MeisterTR** [comment]
ok that seems like a problem with your pi or network and not with this adapter. i cant help with that
