### ISSUE TITLE
LED geht nicht aus, wenn Dimmer auf 0% (Material)

### ISSUE THREAD

**Issue by HansPeterMeier** [iobroker-community-adapters/ioBroker.yeelight-2#24]
Besteht die Möglichkeit bei einem Dimmwert von 0 die LED auszuschalten und umgekehrt?
Würde in der Material Visu helfen.

Gruß und Danke

**Comment by jayfizzle** [comment]
Per Skript sollte das doch möglich sein, muss ja nicht der Adapter können bzw steuern 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HansPeterMeier** [comment]
Das ist richtig, aber dann müsste ich Variablen dafür anlegen und mit dem Script arbeiten. Wenn es direkt im Adapter wäre, wird dieses auch für andere User, die kein Java können interessant. Man benötigt dann auch nur 3 Widget (Color, CT, Dimmer) ansonsten müsste man so jetzt 4 nehmen, da der Power dazukommen würde.

**Comment by ViP3R76** [comment]
Also, von der reinen Logik wäre es sinnvoll, das wenn der Dimmwert = 0% ist -> dann Power Switch = false, ist der Wert >1% dann Power Switch = true. Betrifft bei mir z.B. die Xiaomi Bedlamp.

**Comment by HansPeterMeier** [comment]
So hab ich das jetzt auch gelöst. Alexa sage ich nur noch die %  wie damals bei der hue auch.

**Comment by MeisterTR** [comment]
Sowohl der cloudadapter als auch der Material Adapter sollten die 0% abfangen und den power state betätigen ich bin der Meinung, dass die logik der Yeelights nicht alt so sehr verbogen werden sollte, 0 % geht in der Yeelight app auch nicht. Ich werde aber in Erwägung ziehen, dass so umzusetzen.

**Comment by Rushmed** [comment]
Auch der IOT Adapter schaltet bei 0% nicht power aus.
Habs jetzt auch per Script gelöst.
Aus irgendeinem Grund wird nachdem ich die LED über brightness 0% ausgeschaltet habe der Wert stets nach etwa 30 s von yeelight-2.0/admin wieder auf den vorherigen eingestellt und die Lampe schaltet sich wieder ein.

**Comment by Fruitsmart** [comment]
> Auch der IOT Adapter schaltet bei 0% nicht power aus.
> Habs jetzt auch per Script gelöst.
> Aus irgendeinem Grund wird nachdem ich die LED über brightness 0% ausgeschaltet habe der Wert stets nach etwa 30 s von yeelight-2.0/admin wieder auf den vorherigen eingestellt und die Lampe schaltet sich wieder ein.

Genau das gleiche Problem habe ich.
