### ISSUE TITLE
indicator.connected value switches automatically, Connection lost

### ISSUE THREAD

**Issue by jayfizzle** [iobroker-community-adapters/ioBroker.yeelight-2#25]
Hi,

vieloeicht ist es einfacher wenn man sich auf deutsch unterhält ;).
Dachte es wäre von Vorteil für andere User wenn man es auf Englisch versucht, sollen die Google Translate benutzen.

Die Steuerung der bg_rgb ist behoben, zumindest kann ich nunn da was einstellen.
Aber habe andere Probleme, keine Ahnung ob dies an meinem setup oder anderm Zeug liegt.

Folgende Probleme habe ich mit den Yeelights in Kombination mit dem iobroker, per Yeelight App habe ich keine Probleme.

- Bei Lampen die ausgeschaltet (kein Strom) sind, also nicht per App oder per Sensor usw. wird der Wert von indicator.connected von true auf false gesetzt nach einiger Zeit, dies ist soweit korrekt, jedoch schaltet der Wert hin und wieder zwiaschen true und false obwohl die Lampe weiterhin ausgeschaltet ist und in der zwischenzeit auch nicht eingeschaltet wurde.

- Schalte die Lampen abends aber auch tagsüber komplett aus (per Schalter), nach wieder einschalten habe ich in letzter Zeit dann das Problem das der iobroker die Lampen nicht mehr findet, also die Verbindung scheint anschließend nicht immer wieder aufgebaut zu werden, obwohl sich die IP Adressen der Yeelights auch nicht geändert hat. Wenn ich die Yeelight Instanz dann jedoch neu starte werden die Lampen wieder gefunden.

Hänge mal ein Log an mit der Bitte um Unterstützung, komme da leider nicht wirklcih weiter.
Kann man den yeelight Adapter irgendwie komplett löschen über Console und neu installieren? Nicht das irgendwo irgendwelche Temp Dateien stören usw.

[yeelight_debug.log](https://github.com/MeisterTR/ioBroker.yeelight-2/files/2674779/yeelight_debug.log)

Was mir noch aufgefallen ist das im Log (Debug) einige für mich merkwürdige Werte angezeigt werden.

Die Namen 0x000000000000000 bis 0x000000000000005 sind mir nicht bekannt, die von mir genutzen und über den Adapter gefundenen Lampen haben andere Namen (siehe Log im Anhang)

Was ich bislang versucht habe:
- Yeelight Objekte gelöscht
- Yeelight Adapter gelöscht
- Neuinstallation des Adapters inkl. neuer Suche der Yeelights

Gruß und besten Dank
Jay

**Comment by MeisterTR** [comment]
werden die lampen alle automatisch gefunden?  die ids die 0 bis 5 werden nur vergeben wenn die lampen nicht gefunden wurden. das sollte aber eigentlich kein Problem sein weil die zuordnung über die ip geregelt wird. kannsst du mal einen log anfügen wo alle lampen an sind (mit spannung versorgt)und dann den Adapter starten

**Comment by jayfizzle** [comment]
Danke für die Rückmeldung, die Lampen wurden alle automatisch gefunden.
Werde es heute leider nicht mehr schaffen, aber die Tage nachreichen. Wie genau habe ich vorzugehen, Adapter stoppen, alle yeelights einschalten und anschließend den Adapter starten? 
Habe heute mal spaßeshalber den iobroker auf meinen PC installiert, die Probleme sind auch dort identisch, dies nur zur Info. 
Wollte ein paar Skripte erstellen welche sich auf den indicator.connected beziehen schreiben, muss dies dann vorerst vertagen, aber danke das du dich der Sache annimmst, ist nicht selbstverständlich.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MeisterTR** [comment]
Adapter stoppen -->alle lampen aus der config loschen, und speicher --> dann alle objekte löschen. --> adapter auf debug umstellen falls noch nicht geschehen --> Alle Lampen mit Spannung versorgen --> Adapter einschalten und suchlauf starten --> Speichern und log posten

**Comment by jayfizzle** [comment]
erledigt. siehe Anhang

[yeelight_debug.log](https://github.com/MeisterTR/ioBroker.yeelight-2/files/2681149/yeelight_debug.log)

**Comment by MeisterTR** [comment]
das sieht schon mal gut aus, alle antworten und die objekte wurden auch alle ordentlich erstellt.  ich habe heute auch unregelmaßigkeiten endeckt bei meiner ceiling1 das problem ist, ich wei0 nicht ob die kinder die resetten oder das von selbst geschieht. aber ich werde es beobachten und auch mal die indicator loggen.

**Comment by jayfizzle** [comment]
Heute konnte ich zumindest **nicht** feststellen das die Verbindung komplett gewesen ist. Aber der indicator ist bei mir weiterhin am "tanzen". Danke für die Mühe. Meiner kleiner kommt noch nicht an die Lichtschalter... die Probleme kommen noch. U.a. aus diesem Grund würde ich gerne den indicator nachts prüfen um sicherzustellen das auch alle lampen aus oder zumindest power = false ist. schönes wochenende

**Comment by jayfizzle** [comment]
Hi, also die genannten Probleme mit dem indicator.connected und dem Verbindungsverlust nach ausschalten der Lampen über den Schalter konnte ich über das Wochenende leider reproduzieren. Falls ich irgendwie weiterhelfen kann.... .
Gruß
jay

**Comment by jayfizzle** [comment]
Hi,
hattest du Gelegenheit dich dem Problem zu widmen?

Gruß
Jay

**Comment by MeisterTR** [comment]
kannst mal die Version von git Testen, habe geraden einen pull bestätigt, wahrscheinlich könnte den prob damit auch gelößt sein.

**Comment by jayfizzle** [comment]
Sieht deutlich stabiler und effektiver aus. Die Lampen/Leuchten werden gefunden und können nun gesteruert werden. Es dauert jedoch mit der neusten Version ein wenig länger bis der Adapter soch mit den Lampen/Leuchten verbindet. Ist aber nicht tragisch. Vielen Dank für die Mühe und den tollen Adapter.
