### ISSUE TITLE
Lampe schaltet nach 30 Sekunden den Dimmer auf xx %

### ISSUE THREAD

**Issue by ViP3R76** [iobroker-community-adapters/ioBroker.yeelight-2#29]
Hallöchen,
wenn ich die Xiaomi Bedside Lamp (MUCTD01YL) über ioBroker oder Alexa ausschalte, dann wird nach ca. 30 Sekunden der Dimmer-State wieder > 0% gesetzt und die Lampe schaltet sich mit dem letzten Status wieder ein, da gleichzeitig der Power-State auf "true" gesetzt wird. Ich habe über ein Blockly-Script einmal geschaut (da ja über iobroker/Alexa mit dem Dimm-Wert eingeschaltet wird > 0%) woher der Einschaltbefehl kommt. Der ursprüngliche Trigger ist in dem Fall der Yeelight-2 Adapter. Ich habe mir jetzt im Blockly erst einmal so beholfen das ich in diesem Fall Befehle vom Yeelight-2 Adapter ignoriere in Verbindung mit dem Power-State und so dennoch über ioBroker und Alexa die Lampe ein-/ausschalten kann.

Ich kann leider nicht sagen warum der Adapter nach ~30 Sekunden wieder einen Dimmer-Wert einträgt und gleichzeitig das Power-State auf "true" gesetzt wird. Ich habe keine Timer in der Yeelight App oder dergleichen eingetragen.

**Comment by MeisterTR** [comment]
same as #24

**Comment by Rushmed** [comment]
Cant find the Solution in [#24](https://github.com/iobroker-community-adapters/ioBroker.yeelight-2/issues/24)
