### ISSUE TITLE
Can´t preset a active_bright state

### ISSUE THREAD

**Issue by timae146** [iobroker-community-adapters/ioBroker.yeelight-2#3]
![github](https://user-images.githubusercontent.com/42387818/44459591-84a3a100-a60a-11e8-8eca-ca71f4fc0093.gif)

**Comment by MeisterTR** [comment]
which version debug log?

**Comment by timae146** [comment]
version 0.3.6

debug log:

yeelight-2.0 | 2018-08-27 00:46:48.317 | debug | redis pmessage  io.yeelight-2.0.*  io.yeelight-2.0.color-0x000000000531c5f2.control.active_bright  {"val":"100","ack":true,"ts":1535323608313,"q":0,"from":"system.adapter.yeelight-2.0","user":"system.u
-- | -- | -- | --
yeelight-2.0 | 2018-08-27 00:46:48.304 | debug | Read bright because poweron: 100
yeelight-2.0 | 2018-08-27 00:46:48.300 | debug | redis pmessage  io.yeelight-2.0.*  io.yeelight-2.0.color-0x000000000531c5f2.control.power  {"val":true,"ack":true,"ts":1535323608292,"q":0,"from":"system.adapter.yeelight-2.0","user":"system.user.admin
yeelight-2.0 | 2018-08-27 00:46:48.290 | debug | redis pmessage  io.yeelight-2.0.*  io.yeelight-2.0.color-0x000000000531c5f2.control..color_mode  {"val":false,"ack":true,"ts":1535323608282,"q":0,"from":"system.adapter.yeelight-2.0","user":"system.use
yeelight-2.0 | 2018-08-27 00:46:48.289 | debug | redis pmessage  io.yeelight-2.0.*  io.yeelight-2.0.color-0x000000000531c5f2.control.power  {"val":true,"ack":true,"ts":1535323608277,"q":0,"from":"system.adapter.yeelight-2.0","user":"system.user.admin
yeelight-2.0 | 2018-08-27 00:46:48.288 | debug | power
yeelight-2.0 | 2018-08-27 00:46:48.287 | debug | {"192.168.178.59":"yeelight-2.0.color-0x000000000531c5f2"}
yeelight-2.0 | 2018-08-27 00:46:48.286 | debug | {"power":"on"}
yeelight-2.0 | 2018-08-27 00:46:48.286 | debug | This id:_yeelight-2.0.color-0x000000000531c5f2.control
yeelight-2.0 | 2018-08-27 00:46:48.284 | debug | 192.168.178.59
yeelight-2.0 | 2018-08-27 00:46:48.275 | debug | get_prob:_bright__192.168.178.59__55443
yeelight-2.0 | 2018-08-27 00:46:48.273 | debug | Answer from set_power: ["ok"]
yeelight-2.0 | 2018-08-27 00:46:48.254 | debug | Upload State power host: 192.168.178.59 Port: 55443 Value: true
yeelight-2.0 | 2018-08-27 00:46:48.250 | debug | ["yeelight-2","0","color-0x000000000531c5f2","control","power"]
yeelight-2.0 | 2018-08-27 00:46:48.248 | debug | redis pmessage  io.yeelight-2.0.*  io.yeelight-2.0.color-0x000000000531c5f2.control.power  {"val":true,"ack":false,"ts":1535323608247,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","l
yeelight-2.0 | 2018-08-27 00:46:44.465 | debug | redis pmessage  io.yeelight-2.0.*  io.yeelight-2.0.color-0x000000000531c5f2.control.active_bright  {"val":1,"ack":true,"ts":1535323604463,"q":0,"from":"system.adapter.yeelight-2.0","user":"system.user.
yeelight-2.0 | 2018-08-27 00:46:44.462 | debug | Answer from set_bright: ["ok"]
yeelight-2.0 | 2018-08-27 00:46:44.444 | debug | Upload State active_bright host: 192.168.178.59 Port: 55443 Value: 1
yeelight-2.0 | 2018-08-27 00:46:44.442 | debug | ["yeelight-2","0","color-0x000000000531c5f2","control","active_bright"]

**Comment by MeisterTR** [comment]
fixed on git
