### ISSUE TITLE
Verbindung geht zur yeelight verloren.

### ISSUE THREAD

**Issue by volkerrichert** [iobroker-community-adapters/ioBroker.yeelight-2#30]
Wenn eine yeelight "länger" aus war, dann ist es mir schon mehrfach passiert, dass sie nicht mehr gesteurt werden konnte. Selbst nachdem sie 1/2h oder länger wieder Strom hatte. Erst ein restart des Adapters brachte die Steuerbarkeit zurück.

**Comment by MeisterTR** [comment]
Stell mal unter Instanzen ein, dass der Adapter sich nachts einmal neu starten soll, das Problem hatte ich auch, seit dem er nachts neu startet, ist alles ok

**Comment by volkerrichert** [comment]
a) das finde ich nicht
b) btw, ich komme gerade nicht auf "Einstellung", nur die Geräte in Haupteinstellung kann ich sehen
c) wäre es nicht besser das zu fixen? Ich möchte das Licht nicht er nächsten Tag bedienen können. ;-)

**Comment by volkerrichert** [comment]
ok, zum fix: Ich vermute mal, dass das yeelight-wifi das Problem ist. Es gibt ja einen Grund warum Du das kopiert hast. Wird wohl nicht mehr betreut.... Ich sehe ja, dass du auch eine Fork hast. Warum nutzt due eine kopie im Projekt statt einem Fork? 

Hast du das Issue gesehen? (https://github.com/pmdroid/yeelight-wifi/pull/59). Das ist auch von Autoreconnect die rede. Den könntest Du ja in deinen Fork ziehen. Was hast den bei dir angepasst?

**Comment by MeisterTR** [comment]
Das ist der fix, danach tritt der Fehler nciht mehr auf. Der regelmäßige Neustart der Verbindung scheint bei machen yeelights erforderlich zu sein.

**Comment by MeisterTR** [comment]
yeelight-wif ist da nicht das Problem den pull hab ich bei mir auch drin plus einige andere Connection Anpassungen. Wodurch sich die Verbindung merklich verbessert hat. Ich habe mittlerweile fast alle Yeelight Modelle. Aber nur eine Hat diese art Verbindungsprobleme. also liegt es an den Lampen selber. Ich Schätze dass die Befehle dann zwar bei der Lampe ankommen aber nicht mehr verarbeitet werden. (tritt aber nur bei langen Verbindungen auf  also nach mehreren Tagen).
Ja ich habe auch einen Yeelight-wifi fork habe auch anfangs mit dem gearbeitet, und dann den fork bei der Installation des Adapter mit installiert. Leider kam es hier ztu vielen Problemen bei Nutzern und ich konnte letz endlich nicht ,mehr nachvollziehen wo und in welcher Version die Fehler waren also musste alles an einen Ort. Deswegen kein Fork mehr.

Abhife schafft wie gesagt ein neustart des adapters. bei mir wird er nachts um drei einmal neu gesatartet. bitte versuche es mal und gebe Rückmeldung. wenn es bei dir auch hilft, übernehme ich das fest in den adapter.

![image](https://user-images.githubusercontent.com/6328382/51886100-9abe4600-238e-11e9-8474-32fc577ff188.png)

**Comment by volkerrichert** [comment]
Danke für die ganzen Details, sehr cool. ich habe das Problem mit einer yeelight650 und einer yeelight480. Mal sehen was sich ergibt

Aber sonst ein cooler Adapter. Danke!

**Comment by volkerrichert** [comment]
Ich habe mir das mal ansehen. Wenn die Lampe an war und der adapter sich connected hat und ich die lampe dann ausschalte, dann landet der Code in 

https://github.com/MeisterTR/ioBroker.yeelight-2/blob/master/yeelight-wifi/build/Yeelight.js#L110-L126

Soweit ok. Dann wird bei einem Power off ein CONNRESET ausgelöst und die Verbindung neu aufgebaut. Nur das landet dann im close-event und dann ist Schluss.

`  Yeelight-Badezimmer Connection refresh on Badezimmer id 0x000000000000000 on 192.168.120.29:55443 +30s
  Yeelight-Badezimmer sending req: {"method":"get_prop","params":["power","bright","rgb","color_mode","ct"],"id":8} +12ms
  Yeelight-Badezimmer Connection reset on id 0x000000000000000 192.168.120.29:55443 connection +27s
  Yeelight-Badezimmer connected to Badezimmer id 0x000000000000000 on 192.168.120.29:55443 +1s
  Yeelight-Badezimmer closed connection to Badezimmer id 0x000000000000000 on 192.168.120.29:55443 +2s
  Yeelight-Badezimmer closed connection to Badezimmer id 0x000000000000000 on 192.168.120.29:55443 +21s`

Warum da 2x closed connection steht weiß ich nocht nicht

Lampen die beim Start aus sind werden auch nicht mehr reconnected. Das landet auch im socket close event und dann passiert kein reconnect mehr

BTW, du setzt den Namen im Yeelight immer auf "Living Room", obwohl du da einen Namen hättest.

**Comment by volkerrichert** [comment]
Ich mach mal 2 PRs....

**Comment by MeisterTR** [comment]
erledigt mit pull #31

**Comment by volkerrichert** [comment]
Super, dann spare ich mir die Installation aus meinem fork und warte auf das release !!

**Comment by volkerrichert** [comment]
wann wolltest du das releasen?

**Comment by Pikktee** [comment]
Hat sich hier irgendetwas getan? Ich habe das selbe Problem... Xiaomi Leuchten, die ich vom Strom nehme (also über den nicht-smarten Kippschalter ausschalte) reagieren nach erneutem anschalten nicht, bis ich die Instanz neu gestartet habe.

**Comment by thatso** [comment]
Ich glaube, ich bin ebenfalls davon betroffen. Meine jeweils 2 Yeelight 480 und 650 reagieren nach ziemlich genau 360 Betriebsstunden (=15 Tage) nicht mehr auf Befehle des Adapters. Ein Neustart des Adapters hilft dann auch nicht mehr. Erst, nachdem ich alle Leuchten aus- und wieder einschaltet habe, reagieren sie wieder auf den Adapter. Währenddessen reagieren Sie über die Yeelight App aber weiterhin.

... mäh ... sehe gerade: hier ist ja schon closed.

**Comment by volkerrichert** [comment]
@thatso Sind denn die Lampen in der App noch per WLAN erreichbar? Ich habe den Effekt, dass die Lampen selber wohl WLAN verlieren. Ob das nach 15 Tagen passiert weiß ich nicht, kann aber sein. Es dauert auf jeden Fall länger. Bei mir hilft nur stromlos machen.

Das ist was anderes als der Fehler hier. Hier verliert der Adapter die Connection, obwohl die Lampe online war.

**Comment by thatso** [comment]
@volkerrichert Wie ich schon schrieb: über die App bleiben sie ansteuerbar.
Inzwischen habe ich den weiter oben beschriebenen täglichen Adapterneustart eingerichtet und bin jetzt bei über 520 Stunden korrekter Funktion.
