### ISSUE TITLE
YEELIGHT Meteorite LED Smart Dinner Pendant Lights 

### ISSUE THREAD

**Issue by jayfizzle** [iobroker-community-adapters/ioBroker.yeelight-2#34]
Hi,

wird sich die neue Yeelight Pendellechte (YEELIGHT Meteorite LED Smart Dinner Pendant Lights) über deinen Adapter mit dem ioBroker verbinden lassen?
Wirst du den Adapter entsprechend anpassen um eine Verbindung zu ermöglichen?

Gruß
jay

**Comment by MeisterTR** [comment]
Es sollten alle Yeelights funktionieren sollte die Lampe irgendwelche Zusatzfunktionen haben die über die normale api hinaus gehen, einfach melden und ich kümmere mich drum
