### ISSUE TITLE
Faktisch aus und doch an

### ISSUE THREAD

**Issue by maxpd1** [iobroker-community-adapters/ioBroker.yeelight-2#37]
Ich habe bei dem Adapter das Problem, dass er ziemlich häufig mittels Skript oder Sprachsteuerung die Lampe beispielsweise auf 0% dimmt und Power ausschaltet, die Werte im Objekt ankommen, aber scheinbar nicht bei der Lampe. D.h. für iobroker ist die Lampe aus, für die Yeelight App und die Lampe selber sind Sie aber an.

**Comment by Rushmed** [comment]
Ich habe ein ähnliches Problem beim Ausschalten. Scheinbar wird Ausschalten übernommen aber nach ca. 30 Sec wird der Status auf "on" ohne Grund gewechselt.

**Comment by baststar** [comment]
https://github.com/iobroker-community-adapters/ioBroker.yeelight-2/issues/56#issuecomment-707321098
