### ISSUE TITLE
Add BLE gateway function?

### ISSUE THREAD

**Issue by thatso** [iobroker-community-adapters/ioBroker.yeelight-2#38]
Most of the Yeelight ceiling lights and the bedside lamp include a BLE gateway to connect to BLE enabled sensors like the thermo-/hygrometer to extend their otherwise limited BLE range.
The MiHome app uses this functionality to make sensors readable even if the mobile phone is not in the BLE proximity.
Do you have any plans to make this functionality available in iobroker?

#https://github.com/AlCalzone/ioBroker.ble/issues/111

**Comment by MeisterTR** [comment]
the ble gateway is not a part of the offical api. there is no documentation about the ble gateway connection so its not possible to add it

**Comment by thatso** [comment]
Actually, there is: [Yeelight Blue Message Interface](https://www.yeelight.com/download/yeelight_blue_message_interface_v1.0.pdf).

**Comment by MeisterTR** [comment]
"Actually" that document is from 2013. and it doesnt document the connection between wifi and ble. imho the connection is only ble-->>wifi -->> xiaomi cloud --->>  phone.

**Comment by thatso** [comment]
I'm no coder, but the link looks to me like something to start with exploring.
Pity I'll have to use an ESP32 BLE to WLAN gateway then whilst my ceiling lights already have the necessary hardware but cannot be interfaced.
