### ISSUE TITLE
Gruppen-Support

### ISSUE THREAD

**Issue by ViP3R76** [iobroker-community-adapters/ioBroker.yeelight-2#42]
Hallöchen,

es ist ja auch innerhalb der Yeelight App möglich Gruppen von Leuchtmitteln zu bilden. Wird dies in Zukunft ggf. auch im Adapter möglich sein? Ich habe z.B. im Wohnzimmer drei Yeelight Birnen in einer Lampe (LED - Color Yeelight 2) die ich gerne gruppiert steuern möchte.

**Comment by MeisterTR** [comment]
Das ist ein Feature der app, und nicht der Lampen an sich. Da es leicht in
einem Script umgesetzt werden kann und im Adapter selber sehr aufwendig
wäre. Wird das nicht im Adapter integriert werden.

ToTXR4Y <notifications@github.com> schrieb am Di., 19. Nov. 2019, 15:22:
