### ISSUE TITLE
Yeelight+Alexa+iot-cloud - "aus" schaltet nicht aus

### ISSUE THREAD

**Issue by Carsten0809** [iobroker-community-adapters/ioBroker.yeelight-2#45]
in der iot-cloud eine Gruppe "Deckenfluter" wie folgt angelegt:
1. **power**+**ct**+**hue** hinzugefügt: Lampe ausschalten, Farbtemperatur und Farbwahl funktioniert, aber man kann die Lampe nicht dimmen 
2. **power**+**ct**+**hue**+**active_bright** hinzugefügt: Farbtemperatur und Farbwahl funktionieren, jetzt kann man dimmen (1-100%), aber nicht mehr ausschalten (weder mit "Alexa, schalte Deckenfluter aus", noch mit "Alexa, dimme/setze Deckenfluter auf 0%") 
Es wird zwar kurzfristig der Wert von **active_bright** auf _0%_ gesetzt, aber die Lampe reagiert nicht darauf und der Wert setzt sich automatisch wieder auf den Ausgangswert zurück. **power** bleibt die ganze Zeit auf _true_

**Comment by MeisterTR** [comment]
In der Config vom Adapter gibt es den Unterpunkt smartname, nutzt du den nicht? Wenn hier etwas eingetragen ist, sollte im iot Adapter alles richtig angelegt sein und richtig funktionieren oder nicht?

**Comment by Carsten0809** [comment]
leider "oder nicht", deswegen habe ich das ja alles manuell angelegt. im iot-Adapter taucht mein "Deckenfluter" trotz Smartname nicht auf.

 aber es scheint ja anscheinend kein Adapter-Fehler zu sein, sondern mein Unvermögen, sonst wäre das ja schon jemand anderem aufgefallen. Ich versuch mein Glück noch mal im Forum. Danke ;-)

**Comment by MeisterTR** [comment]
![2020-01-02_22h14_54](https://user-images.githubusercontent.com/6328382/71693671-552fa780-2dad-11ea-9b64-2cdc2dfb38a0.png)
So muss die eintellung aussehen, der wert 0 wird nicht unterstützt, bei schalte aus, sollte der power wert geändert werden

**Comment by Carsten0809** [comment]
ich hab es jetzt genau so gebaut (sprich mit allen 5) und es bleibt wie ich es beschrieben habe. "Alexa, schalte Deckenfluter aus" setzt nur active_bright auf 0% und sonst passiert nichts. Lasse ich active_bright weg, dann schaltet Alexa die Lampe aus, aber ich kann nicht mehr dimmen... keine Ahnung was da bei mir falsch ist.

![1](https://user-images.githubusercontent.com/59436648/71694436-798c8380-2daf-11ea-8b47-c4024ca168a7.jpg)
![2](https://user-images.githubusercontent.com/59436648/71694437-7a251a00-2daf-11ea-99e5-c172dc38b73a.jpg)

**Comment by MeisterTR** [comment]
das magische wort heißt `"byON" :"-"`  in dem raw objekt. Dies ist aber kein adapter fehler sondern eher vom iot
![2020-02-11_22h37_31](https://user-images.githubusercontent.com/6328382/74281948-9ce80e00-4d1f-11ea-960e-af8306fc2e3c.png)
