### ISSUE TITLE
Hoher Arbeitsspeicherverbrauch bei offline Lampen

### ISSUE THREAD

**Issue by peoples0815** [iobroker-community-adapters/ioBroker.yeelight-2#46]
Hi,
ich habe im Forum auch schon einen Thread eröffnet ohne Feedback, deswegen schreibe ich es hier nochmal.
Ich hatte den Adapter ca. 60 Tage am Laufen und hatte einen Arbeitsspeicher-Verbauch von 650 MB. Ist das normal? Beim löschen der Instanz gab es auch über 3000 Elemente die gelöscht wurden und das bei 4 angelernten Geräten

Vielleicht kann sich jemand das mal näher anschauen

**Comment by MeisterTR** [comment]
nein das ist nicht normal. normalerweise so um die 60 mb lösche den adapter mal und installiere ihn neu und dann nochmal beobachten

**Comment by peoples0815** [comment]
So erledigt, ein Ta gelaufen und wieder 100 MB bei 5 Lampen

Legt der Adapter irgendwo Logs an oder ähnliches?

**Comment by MeisterTR** [comment]
Ein Debug logauszug wäre super

**Comment by peoples0815** [comment]
Es hat nun einige Zeit gedauert, aber nun kann ich nach vielem Testen sagen woran es bei mir liegt!

Wenn ich Lampen eintrage die offline sind, bspw. welche die über einen richtigen Lichtschalter ausgeschalten sind, benötigt der Adapter immer mehr Arbeitsspeicher. Dieses Verhalten habe ich bestimmt 5 mal neu nachgestellt. 
Erst nur Lampen die online sind, da tummelt sicher der Adapter um die 60 MB. Sobald ich meine drei Lampen eintrage die wirklich stromlos / somit nicht erreichbar sind, steigt der Arbeitsspeicher endlos an.

**Comment by MeisterTR** [comment]
das ist super oder besser gesagt nicht, aber so weiß ich wo ich suchen muss..
