### ISSUE TITLE
Yeelight yldp02yl

### ISSUE THREAD

**Issue by altbau9944** [iobroker-community-adapters/ioBroker.yeelight-2#47]
Hallo zusammen,

ich bekomme meine Yeelight yldp02yl nicht eingebunden.

Kann mir jemand hier helfen?

Gruß

**Comment by MeisterTR** [comment]
ein paar mehr infos wären ganz hilfreich

**Comment by altbau9944** [comment]
Guten Morgen,

ich habe ioBroker in der aktuellen Version installiert auf einem Raspi 4 mit 4 GB installiert und auch alle Adapter auf dem neusten Stand.
Der Yeelight 2.0 Adapter erkennt meine Ceiling Deckenlampe direkt und diese kann auch gesteuert werden.
Wenn ich die jetzt versuche diese Yeelight yldp02yl einzubinden, wird diese nicht vollständig unter den Objekten intigriert.
D.h. Kein Controll - Ordner....

Wird diese Yeelight yldp02yl überhaupt unterstüzt?

Gruß

**Comment by MeisterTR** [comment]
Wird sie denn gefunden? Ist due lan Steuerung der Lampe aktiviert? (siehe readme) bei manchen ist sie standardmäßig aus bei manchen an..

**Comment by altbau9944** [comment]
Hi,
Die yeelight wird nicht automatisch gefunden. Nur wenn ich diese in dem Adapter manuell eintrage.

Die Lan Steuerung ist aktiviert. Hatte ja früher unter Openhab schon mal funktioniert..

**Comment by MeisterTR** [comment]
versuch mal bitte die lampe zu resetten und neu inst wlan ein zu binden, es kann vorkommen, dass sich die Lansteuerung aufhängt und dann geht es erst anch einem reset wieder

**Comment by altbau9944** [comment]
Mahlzeit..

Hat geklappt!! Nach Reset und Freigabe der Lan-Steuerung wurde die Lampe gefunden und richtig eingebunden!!

Vielen Dank!
