### ISSUE TITLE
Error if i want to search for new devices

### ISSUE THREAD

**Issue by timae146** [iobroker-community-adapters/ioBroker.yeelight-2#5]
if i want to serach for new devices i get this errors in the log:
if i insert ip name and port manually it works

yeelight-2.0 | 2018-08-27 13:48:50.206 | debug | Create Device: yeelight-2.0.color-
-- | -- | -- | --
yeelight-2.0 | 2018-08-27 13:48:48.199 | debug | der sm:
yeelight-2.0 | 2018-08-27 13:48:48.198 | debug | hier die ate cfg: {"name":"","ip":"","port":"","smart_name":"","type":"color"}
yeelight-2.0 | 2018-08-27 13:48:48.194 | debug | Element:_yeelight-2.0.color-
yeelight-2.0 | 2018-08-27 13:48:48.193 | debug | count Devices:_1
yeelight-2.0 | 2018-08-27 13:48:48.193 | debug | found  Devices:_{"yeelight-2.0.color-":{"type":"device","common":{"name":"color","icon":"/icons/color.png"},"native":{"sid":"","type":"color"},"from":"system.adapter.yeelight-2.0","user":"system.user.
yeelight-2.0 | 2018-08-27 13:48:48.143 | debug | from_conf: {"devices":[{"name":"","ip":"","port":"","smart_name":"","type":"color"}]}
yeelight-2.0 | 2018-08-27 13:48:48.104 | info | starting. Version 0.3.6 in /opt/iobroker/node_modules/iobroker.yeelight-2, node: v8.11.1
yeelight-2.0 | 2018-08-27 13:48:48.063 | info | States connected to redis: 127.0.0.1:6379
yeelight-2.0 | 2018-08-27 13:48:48.057 | debug | statesDB connected
yeelight-2.0 | 2018-08-27 13:48:48.024 | debug | objectDB connected
host.ioBroker-RasPi | 2018-08-27 13:48:46.836 | info | instance system.adapter.yeelight-2.0 started with pid 2560
host.ioBroker-RasPi | 2018-08-27 13:48:16.805 | info | Restart adapter system.adapter.yeelight-2.0 because enabled
host.ioBroker-RasPi | 2018-08-27 13:48:16.805 | error | instance system.adapter.yeelight-2.0 terminated with code 0 (OK)
Caught | 2018-08-27 13:48:16.805 | error | by controller[1]:     at Socket.emit (events.js:211:7)
Caught | 2018-08-27 13:48:16.805 | error | by controller[1]:     at emitOne (events.js:116:13)
Caught | 2018-08-27 13:48:16.805 | error | by controller[1]:     at Socket.<anonymous> (/opt/iobroker/node_modules/redis/index.js:274:27)
Caught | 2018-08-27 13:48:16.805 | error | by controller[1]:     at JavascriptRedisParser.execute (/opt/iobroker/node_modules/redis-parser/lib/parser.js:574:12)
Caught | 2018-08-27 13:48:16.804 | error | by controller[1]:     at JavascriptRedisParser.returnReply (/opt/iobroker/node_modules/redis/index.js:192:18)
Caught | 2018-08-27 13:48:16.804 | error | by controller[1]:     at RedisClient.return_reply (/opt/iobroker/node_modules/redis/index.js:824:9)
Caught | 2018-08-27 13:48:16.804 | error | by controller[1]:     at normal_reply (/opt/iobroker/node_modules/redis/index.js:726:21)
Caught | 2018-08-27 13:48:16.804 | error | by controller[1]:     at Command.callback  (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:267:49)
Caught | 2018-08-27 13:48:16.804 | error | by controller[1]:     at that.states.getStates (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4632:61)
Caught | 2018-08-27 13:48:16.804 | error | by controller[1]:     at /opt/iobroker/node_modules/iobroker.yeelight-2/main.js:1361:33
Caught | 2018-08-27 13:48:16.804 | error | by controller[1]: TypeError: Cannot set property '' of null
Caught | 2018-08-27 13:48:16.803 | error | by controller[0]:     at Timer.listOnTimeout (timers.js:277:5)
Caught | 2018-08-27 13:48:16.803 | error | by controller[0]:     at tryOnTimeout (timers.js:317:5)
Caught | 2018-08-27 13:48:16.803 | error | by controller[0]:     at ontimeout (timers.js:482:11)
Caught | 2018-08-27 13:48:16.803 | error | by controller[0]:     at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:158:37)
Caught | 2018-08-27 13:48:16.803 | error | by controller[0]:     at createDevice (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:322:9)
Caught | 2018-08-27 13:48:16.803 | error | by controller[0]:     at getPrps (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:333:15)
Caught | 2018-08-27 13:48:16.802 | error | by controller[0]:     at Yeelight.sendCommand (/opt/iobroker/node_modules/iobroker.yeelight-2/lib/yeelight.js:47:19)
Caught | 2018-08-27 13:48:16.802 | error | by controller[0]:     at Object.connect (net.js:113:35)
Caught | 2018-08-27 13:48:16.802 | error | by controller[0]:     at Socket.connect (net.js:1037:5)
Caught | 2018-08-27 13:48:16.802 | error | by controller[0]:     at lookupAndConnect (net.js:1064:13)
Caught | 2018-08-27 13:48:16.801 | error | by controller[0]: RangeError: "port" option should be >= 0 and < 65536:
yeelight-2.0 | 2018-08-27 13:48:16.787 | info | terminating
yeelight-2.0 | 2018-08-27 13:48:16.342 | error | Error: connect ECONNREFUSED 127.0.0.1:55443
yeelight-2.0 | 2018-08-27 13:48:16.341 | error | Error: connect ECONNREFUSED 127.0.0.1:55443
yeelight-2.0 | 2018-08-27 13:48:16.334 | debug | listen to: :55443
yeelight-2.0 | 2018-08-27 13:48:16.326 | debug | Update connection for:_yeelight-2.0.color-
yeelight-2.0 | 2018-08-27 13:48:16.319 | error | at Socket.emit (events.js:211:7)
yeelight-2.0 | 2018-08-27 13:48:16.319 | error | at emitOne (events.js:116:13)
yeelight-2.0 | 2018-08-27 13:48:16.319 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/redis/index.js:274:27)
yeelight-2.0 | 2018-08-27 13:48:16.319 | error | at JavascriptRedisParser.execute (/opt/iobroker/node_modules/redis-parser/lib/parser.js:574:12)
yeelight-2.0 | 2018-08-27 13:48:16.319 | error | at JavascriptRedisParser.returnReply (/opt/iobroker/node_modules/redis/index.js:192:18)
yeelight-2.0 | 2018-08-27 13:48:16.319 | error | at RedisClient.return_reply (/opt/iobroker/node_modules/redis/index.js:824:9)
yeelight-2.0 | 2018-08-27 13:48:16.319 | error | at normal_reply (/opt/iobroker/node_modules/redis/index.js:726:21)
yeelight-2.0 | 2018-08-27 13:48:16.319 | error | at Command.callback (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:267:49)
yeelight-2.0 | 2018-08-27 13:48:16.319 | error | at that.states.getStates (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4632:61)
yeelight-2.0 | 2018-08-27 13:48:16.319 | error | at /opt/iobroker/node_modules/iobroker.yeelight-2/main.js:1361:33
yeelight-2.0 | 2018-08-27 13:48:16.319 | error | TypeError: Cannot set property '' of null
yeelight-2.0 | 2018-08-27 13:48:16.318 | error | uncaught exception: Cannot set property '' of null
yeelight-2.0 | 2018-08-27 13:48:16.303 | debug | sid by socket:_["yeelight-2","0","color-","info","IPAdress"]
yeelight-2.0 | 2018-08-27 13:48:16.280 | error | at Timer.listOnTimeout (timers.js:277:5)
yeelight-2.0 | 2018-08-27 13:48:16.280 | error | at tryOnTimeout (timers.js:317:5)
yeelight-2.0 | 2018-08-27 13:48:16.280 | error | at ontimeout (timers.js:482:11)
yeelight-2.0 | 2018-08-27 13:48:16.280 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:158:37)
yeelight-2.0 | 2018-08-27 13:48:16.280 | error | at createDevice (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:322:9)
yeelight-2.0 | 2018-08-27 13:48:16.280 | error | at getPrps (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:333:15)
yeelight-2.0 | 2018-08-27 13:48:16.280 | error | at Yeelight.sendCommand (/opt/iobroker/node_modules/iobroker.yeelight-2/lib/yeelight.js:47:19)
yeelight-2.0 | 2018-08-27 13:48:16.280 | error | at Object.connect (net.js:113:35)
yeelight-2.0 | 2018-08-27 13:48:16.280 | error | at Socket.connect (net.js:1037:5)
yeelight-2.0 | 2018-08-27 13:48:16.280 | error | at lookupAndConnect (net.js:1064:13)
yeelight-2.0 | 2018-08-27 13:48:16.280 | error | RangeError: "port" option should be >= 0 and < 65536:
yeelight-2.0 | 2018-08-27 13:48:16.279 | error | uncaught exception: "port" option should be >= 0 and < 65536:
yeelight-2.0 | 2018-08-27 13:48:16.257 | debug | Create Device: yeelight-2.0.color-
yeelight-2.0 | 2018-08-27 13:48:14.248 | debug | der sm:
yeelight-2.0 | 2018-08-27 13:48:14.247 | debug | hier die ate cfg: {"name":"","ip":"","port":"","smart_name":"","type":"color"}
yeelight-2.0 | 2018-08-27 13:48:14.243 | debug | Element:_yeelight-2.0.color-
yeelight-2.0 | 2018-08-27 13:48:14.243 | debug | count Devices:_1
yeelight-2.0 | 2018-08-27 13:48:14.242 | debug | found  Devices:_{"yeelight-2.0.color-":{"type":"device","common":{"name":"color","icon":"/icons/color.png"},"native":{"sid":"","type":"color"},"from":"system.adapter.yeelight-2.0","user":"system.user.
yeelight-2.0 | 2018-08-27 13:48:14.191 | debug | from_conf: {"devices":[{"name":"","ip":"","port":"","smart_name":"","type":"color"}]}
yeelight-2.0 | 2018-08-27 13:48:14.151 | info | starting. Version 0.3.6 in /opt/iobroker/node_modules/iobroker.yeelight-2, node: v8.11.1
yeelight-2.0 | 2018-08-27 13:48:14.109 | info | States connected to redis: 127.0.0.1:6379
yeelight-2.0 | 2018-08-27 13:48:14.102 | debug | statesDB connected
yeelight-2.0 | 2018-08-27 13:48:14.068 | debug | objectDB connected

**Comment by MeisterTR** [comment]
please try to delete all states and reinstall the adapter
