### ISSUE TITLE
cant conrol yeelight pedant 

### ISSUE THREAD

**Issue by 0x1234567890** [iobroker-community-adapters/ioBroker.yeelight-2#50]
The yeelight meteroite pedant light cannot be controlled with me. 
I have activated the LAN mode and am also connected to the lamp. But I can't control it, I can only see the status. 

When I try to set the power status to true, it flashes red.
What could be the reason?

**Comment by MeisterTR** [comment]
a debug log would be nice, without a log it could be everything

**Comment by 0x1234567890** [comment]
**first time turn on:** 

yeelight-2.0 | 2020-02-27 13:29:52.318 | debug | (7739) ERROR YEELIGHT CONNECTION: 0x000000000000000: Connection 192.168.178.30:55443: Error: This socket has been ended by the other party
-- | -- | -- | --
yeelight-2.0 | 2020-02-27 13:29:52.316 | debug | (7739) SEND STATE: id:0x000000000000000, state: power, value: true

**second time:**

yeelight-2.0 | 2020-02-27 13:31:30.609 | debug | (7739) ERROR YEELIGHT CONNECTION: 5: Error: client quota exceeded: undefined
-- | -- | -- | --
yeelight-2.0 | 2020-02-27 13:31:30.578 | debug | (7739) SEND STATE: id:0x000000000000000, state: power, value: true

---

**Connected Status:** 
connect | Connect | state | indicator.connected |   |   | true
-- | -- | -- | -- | -- | -- | --

---

The Yeelight and mi home App work without problems. 


and some of this messages:

yeelight-2.0 | 2020-02-27 21:41:46.635 | debug | (3138) ERROR YEELIGHT CONNECTION: 0x000000000000000: Connection 192.168.178.30:55443: Error: connect EALREADY 192.168.178.30:55443 - Local (192.168.178.23:60036)
-- | -- | -- | --
yeelight-2.0 | 2020-02-27 21:41:43.518 | debug | (3138) ERROR YEELIGHT CONNECTION: 0x000000000000000: Connection 192.168.178.30:55443: Error: connect EALREADY 192.168.178.30:55443 - Local (192.168.178.23:60024)
yeelight-2.0 | 2020-02-27 21:41:42.233 | debug | (3138) ERROR YEELIGHT CONNECTION: 0x000000000000000: Connection 192.168.178.30:55443: Error: connect EHOSTUNREACH 192.168.178.30:55443
yeelight-2.0 | 2020-02-27 21:41:36.002 | debug | (3138) ERROR YEELIGHT CONNECTION: 0x000000000000000: Connection 192.168.178.30:55443: Error: connect EHOSTUNREACH 192.168.178.30:55443
yeelight-2.0 | 2020-02-27 21:41:35.448 | debug | (3138) ERROR YEELIGHT CONNECTION: 0x000000000000000: Connection 192.168.178.30:55443: Error: connect EALREADY 192.168.178.30:55443 - Local (192.168.178.23:59996)
yeelight-2.0 | 2020-02-27 21:41:30.403 | debug | (3138) ERROR YEELIGHT CONNECTION: 0x000000000000000: Connection 192.168.178.30:55443: Error: connect EALREADY 192.168.178.30:55443 - Local (192.168.178.23:59994)

**Comment by MeisterTR** [comment]
please reset the light, then it should work
