### ISSUE TITLE
adapter sets power.val of bslamp2 sporadically to false without turning it off

### ISSUE THREAD

**Issue by jlssmt** [iobroker-community-adapters/ioBroker.yeelight-2#56]
Hello,

my bedside lamp 2 sets its control.power.val sporadically to false without turning its lamp really off. After few seconds it will automatically set to true again.
It's no problem in normal use, but if you want to control the whole room with the hardware keys of the bslamp2 (if bslamp2 turns off -> turn all off) it causes issues, because other lamps, except the bslamp2 will turn off.

I can only provide the events, because there is nothing noted in the logs (imo).

Thanks in advance!

![image](https://user-images.githubusercontent.com/42897917/79079286-873a9900-7d0e-11ea-98a9-845f9725ed27.png)

**Comment by Rushmed** [comment]
I also have this misbehavior.
Solution is needed!

**Comment by baststar** [comment]
This function is called every 60 seconds and sets the state (.control.power) to false, if element.status !== 3

actually i dont know if it is really necessary to turn off the light, if the light is wrongly detected as offline...
@MeisterTR ? :-) 
...

```
function checkOnline() {
    let lights = Yeelights.yeelights;

    if (lights.length !== 0) {
        lights.forEach(element => {
            let device = ConfigDevices.find(device => device.id === element.id);
            if (device) {
                let sid = device.name;

                if (element.status !== 3) {
                    //turn off
                    adapter.setState(sid + '.info.connect', false, true);
                    adapter.setState(sid + '.control.power', false, true);
                    adapter.log.debug('YEELIGHT OFFLINE: ' + element.id);

                } else {
                    //turn on
                    adapter.setState(sid + '.info.connect', true, true);
                }
            }
        });
    }
}
```

**Comment by unstressable** [comment]
Same problem here.
I set the state of my yeelights to "false" and it instantly switches to "true" withoud reason.

I made my scripts to repeat the "false" command 3 or 4 times then it mostly stays "false" mostly, but not every time!

The adapter is quite old and has a lot of bugs. Is there no future update?

**Comment by jlssmt** [comment]
same problem with pendant yeelight
I have to write a workaround with at least 1min timeout, because my latest measure says it stays for 51sec off, before turning on again.
