### ISSUE TITLE
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by kueppert** [iobroker-community-adapters/ioBroker.yeelight-2#57]
Hallo,
ich erhalte seit neuestem folgende Fehlermeldungen. Installiert ist

JS-Controller: 3.0.7
NPM: 6.14.4
Node.js: 13.12.0

```
yeelight-2.0	2020-04-13 08:04:12.428	info	(18850) Terminated (NO_ERROR): Without reason
yeelight-2.0	2020-04-13 08:04:12.427	info	(18850) terminating
yeelight-2.0	2020-04-13 08:04:12.419	info	(18850) cleaned everything up...
yeelight-2.0	2020-04-13 08:04:12.417	error	at processImmediate (internal/timers.js:456:21)
yeelight-2.0	2020-04-13 08:04:12.417	error	at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5303:34)
yeelight-2.0	2020-04-13 08:04:12.417	error	at Adapter.emit (events.js:315:20)
yeelight-2.0	2020-04-13 08:04:12.417	error	at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:44:21)
yeelight-2.0	2020-04-13 08:04:12.417	error	at uploadState (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:116:37)
yeelight-2.0	2020-04-13 08:04:12.417	error	at Yeelight.turnOn (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:530:19)
yeelight-2.0	2020-04-13 08:04:12.417	error	at Yeelight.sendRequest (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:211:14)
yeelight-2.0	2020-04-13 08:04:12.417	error	at new Promise (<anonymous>)
yeelight-2.0	2020-04-13 08:04:12.417	error	at /opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:216:23
yeelight-2.0	2020-04-13 08:04:12.417	error	at module.exports.internals.Any.root.validate (/opt/iobroker/node_modules/joi/lib/index.js:139:23)
yeelight-2.0	2020-04-13 08:04:12.417	error	at internals.Array._validateWithOptions (/opt/iobroker/node_modules/joi/lib/types/any/index.js:672:20)
yeelight-2.0	2020-04-13 08:04:12.417	error	at /opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:232:27
yeelight-2.0	2020-04-13 08:04:12.417	error	at Socket.Writable.write (_stream_writable.js:288:11)
yeelight-2.0	2020-04-13 08:04:12.417	error	(18850) Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
yeelight-2.0	2020-04-13 08:04:12.415	error	(18850) uncaught exception: Cannot call write after a stream was destroyed

```

**Comment by simatec** [comment]
Kann den Fehler bestätigen. Nach Update meines Produktivsystem von js-controller 2.2.9 auf 3.1.4 tritt folgender Fehler beim einschalten von Leuchten auf.

```
2020-05-24 20:55:24.865 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2020-05-24 20:55:24.875 - error: yeelight-2.0 (29160) unhandled promise rejection: Cannot call write after a stream was destroyed
2020-05-24 20:55:24.879 - error: yeelight-2.0 (29160) Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
at doWrite (_stream_writable.js:411:19)
at writeOrBuffer (_stream_writable.js:399:5)
at Socket.Writable.write (_stream_writable.js:299:11)
at /opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:232:27
at internals.Array._validateWithOptions (/opt/iobroker/node_modules/joi/lib/types/any/index.js:672:20)
at module.exports.internals.Any.root.validate (/opt/iobroker/node_modules/joi/lib/index.js:139:23)
at /opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:216:23
at new Promise ()
at Yeelight.sendRequest (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:211:14)
at Yeelight.turnOn (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:530:19)
at uploadState (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:116:37)
at Adapter. (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:44:21)
at Adapter.emit (events.js:198:13)
at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5388:34)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)

```

**Comment by thurbo** [comment]
Das gleiche Problem bei mir. Heute Update gemacht auf Node.js 12.17.0 und JS-Controller 3.1.4.

> 

yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at processImmediate (internal/timers.js:456:21)
-- | -- | -- | --
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5388:34)
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at Adapter.emit (events.js:315:20)
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:44:21)
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at uploadState (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:121:37)
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at Yeelight.turnOff (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:576:19)
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at Yeelight.sendRequest (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:211:14)
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at new Promise (<anonymous>)
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at /opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:216:23
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at module.exports.internals.Any.root.validate (/opt/iobroker/node_modules/joi/lib/index.js:147:23)
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at internals.Array._validateWithOptions (/opt/iobroker/node_modules/joi/lib/types/any/index.js:767:20)
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at /opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:232:27
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at Socket.Writable.write (_stream_writable.js:318:11)
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at writeOrBuffer (_stream_writable.js:387:5)
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | at doWrite (_stream_writable.js:399:19)
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | (30803) Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
yeelight-2.0 | 2020-05-29 23:53:58.816 | error | (30803) unhandled promise rejection: Cannot call write after a stream was destroyed

**Comment by telefonmann14** [comment]
Die selben Fehlermeldungen treten bei mir auch auf.

**Comment by Lumumba76** [comment]
Tja, scheint sich niemand für verantwortlich zu fühlen :-(
