### ISSUE TITLE
Yeelight adapter no longer works since yesterday.

### ISSUE THREAD

**Issue by ArchGithub** [iobroker-community-adapters/ioBroker.yeelight-2#62]
I installed some updates yesterday. After that nothing works anymore with the Yeelights. I have tried to switch the lamps on/off in the objects. Unfortunately nothing works anymore.
![1](https://user-images.githubusercontent.com/38007195/88491061-46564f80-cfa0-11ea-8d55-9d8fd051f7ee.JPG)

**Comment by MeisterTR** [comment]
Witch updates? Debug log!?
