### ISSUE TITLE
SyntaxError yeelight Unexpected token

### ISSUE THREAD

**Issue by plbartek89** [iobroker-community-adapters/ioBroker.yeelight-2#7]
```
yeelight-2.0 | 2018-09-08 00:19:46.118 | error | SyntaxError: Unexpected token { in JSON at position 27
-- | -- | -- | --
yeelight-2.0 | 2018-09-08 00:19:36.768 | error | SyntaxError: Unexpected token { in JSON at position 50
yeelight-2.0 | 2018-09-08 00:19:32.203 | error | SyntaxError: Unexpected token { in JSON at position 27
yeelight-2.0 | 2018-09-08 00:19:13.524 | error | SyntaxError: Unexpected token { in JSON at position 81
yeelight-2.0 | 2018-09-08 00:19:10.172 | error | SyntaxError: Unexpected token { in JSON at position 78
```
I have following error when i try to switch on or off my yeelight 650 or Ceiling Light.
can u help ?
thx

**Comment by MeisterTR** [comment]
can you set log of yeelight to debug an send a cut of the log again..

**Comment by plbartek89** [comment]
![a0e1a9b737e3219b13276568f81ad34e](https://user-images.githubusercontent.com/43064608/45253355-1844d380-b366-11e8-989b-24614053446b.png)

**Comment by MeisterTR** [comment]
tab instance, set expert mode on top and change right side of the adapter from info to debug, than switch the light an paste the log (text ) here.

https://www.youtube.com/watch?v=-1PCHancttc

**Comment by plbartek89** [comment]
`

yeelight-2.0 | 2018-09-10 21:32:51.337 | debug | init_power_opt
-- | -- | -- | --
yeelight-2.0 | 2018-09-10 21:32:51.337 | debug | lan_ctrl
yeelight-2.0 | 2018-09-10 21:32:51.337 | debug | miband_sleep
yeelight-2.0 | 2018-09-10 21:32:51.337 | debug | active_bright
yeelight-2.0 | 2018-09-10 21:32:51.337 | debug | nighttime
yeelight-2.0 | 2018-09-10 21:32:51.336 | debug | ct
yeelight-2.0 | 2018-09-10 21:32:51.336 | debug | bright
yeelight-2.0 | 2018-09-10 21:32:51.336 | debug | name
yeelight-2.0 | 2018-09-10 21:32:51.336 | debug | delayoff
yeelight-2.0 | 2018-09-10 21:32:51.328 | debug | active_mode
yeelight-2.0 | 2018-09-10 21:32:51.328 | debug | flow_params
yeelight-2.0 | 2018-09-10 21:32:51.328 | debug | flowing
yeelight-2.0 | 2018-09-10 21:32:51.328 | debug | nl_br
yeelight-2.0 | 2018-09-10 21:32:51.328 | debug | save_state
yeelight-2.0 | 2018-09-10 21:32:51.327 | debug | power
yeelight-2.0 | 2018-09-10 21:32:51.327 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer","192.168.178.30":"yeelight-2.0.ceiling1-0x0000000004a2035d"}
yeelight-2.0 | 2018-09-10 21:32:51.327 | debug | {"power":"on","save_state":0,"nl_br":0,"flowing":0,"flow_params":"","active_mode":0,"delayoff":0,"name":"","bright":100,"ct":3907,"nighttime":"disable\|220000\|060000\|00","active_bright":100,"miband_sle
yeelight-2.0 | 2018-09-10 21:32:51.327 | debug | This id:_yeelight-2.0.ceiling1-0x0000000004a2035d.control
yeelight-2.0 | 2018-09-10 21:32:51.326 | debug | 192.168.178.30
yeelight-2.0 | 2018-09-10 21:32:46.313 | debug | regest  params from:yeelight-2.0.ceiling1-0x0000000004a2035d.control  _params:_["on","100","3907","","0","2","100","","","0","","","","","","","",""]
yeelight-2.0 | 2018-09-10 21:32:36.771 | debug | Wrong respons at power on, ckeck again --> off  <<--soll ist-->> off
yeelight-2.0 | 2018-09-10 21:32:36.736 | debug | get_prob:_power__192.168.178.41__55443
yeelight-2.0 | 2018-09-10 21:32:36.736 | debug | bg_power
yeelight-2.0 | 2018-09-10 21:32:36.735 | debug | power
yeelight-2.0 | 2018-09-10 21:32:36.735 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer","192.168.178.30":"yeelight-2.0.ceiling1-0x0000000004a2035d"}
yeelight-2.0 | 2018-09-10 21:32:36.735 | debug | {"power":"off","bg_power":"off"}
yeelight-2.0 | 2018-09-10 21:32:36.735 | debug | This id:_yeelight-2.0.ceiling4-Schlafzimmer.control
yeelight-2.0 | 2018-09-10 21:32:36.734 | debug | 192.168.178.41
yeelight-2.0 | 2018-09-10 21:32:36.705 | debug | Error verifying power_on command
yeelight-2.0 | 2018-09-10 21:32:36.649 | debug | Wrong respons at power on, ckeck again --> on  <<--soll ist-->> off
yeelight-2.0 | 2018-09-10 21:32:36.613 | error | SyntaxError: Unexpected token { in JSON at position 50
yeelight-2.0 | 2018-09-10 21:32:36.613 | debug | get_prob:_power__192.168.178.41__55443
yeelight-2.0 | 2018-09-10 21:32:36.613 | debug | main_power
yeelight-2.0 | 2018-09-10 21:32:36.613 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer","192.168.178.30":"yeelight-2.0.ceiling1-0x0000000004a2035d"}
yeelight-2.0 | 2018-09-10 21:32:36.613 | debug | {"main_power":"off"}
yeelight-2.0 | 2018-09-10 21:32:36.613 | debug | This id:_yeelight-2.0.ceiling4-Schlafzimmer.control
yeelight-2.0 | 2018-09-10 21:32:36.570 | debug | 192.168.178.41
yeelight-2.0 | 2018-09-10 21:32:36.519 | debug | Upload State power host: 192.168.178.41 Port: 55443 Value: false
yeelight-2.0 | 2018-09-10 21:32:36.505 | debug | ["yeelight-2","0","ceiling4-Schlafzimmer","control","power"]
yeelight-2.0 | 2018-09-10 21:32:30.510 | error | SyntaxError: Unexpected token { in JSON at position 78
yeelight-2.0 | 2018-09-10 21:32:30.510 | debug | bg_power
yeelight-2.0 | 2018-09-10 21:32:30.510 | debug | main_power
yeelight-2.0 | 2018-09-10 21:32:30.509 | debug | power
yeelight-2.0 | 2018-09-10 21:32:30.509 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer","192.168.178.30":"yeelight-2.0.ceiling1-0x0000000004a2035d"}
yeelight-2.0 | 2018-09-10 21:32:30.509 | debug | {"power":"on","main_power":"on","bg_power":"on"}
yeelight-2.0 | 2018-09-10 21:32:30.509 | debug | This id:_yeelight-2.0.ceiling4-Schlafzimmer.control
yeelight-2.0 | 2018-09-10 21:32:30.508 | debug | 192.168.178.41
yeelight-2.0 | 2018-09-10 21:32:30.474 | debug | Upload State power host: 192.168.178.41 Port: 55443 Value: true
yeelight-2.0 | 2018-09-10 21:32:30.453 | debug | ["yeelight-2","0","ceiling4-Schlafzimmer","control","power"]
yeelight-2.0 | 2018-09-10 21:32:18.606 | debug | Wrong respons at power on, ckeck again --> off  <<--soll ist-->> off
yeelight-2.0 | 2018-09-10 21:32:18.554 | debug | get_prob:_power__192.168.178.41__55443
yeelight-2.0 | 2018-09-10 21:32:18.554 | debug | bg_power
yeelight-2.0 | 2018-09-10 21:32:18.554 | debug | power
yeelight-2.0 | 2018-09-10 21:32:18.554 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer","192.168.178.30":"yeelight-2.0.ceiling1-0x0000000004a2035d"}
yeelight-2.0 | 2018-09-10 21:32:18.554 | debug | {"power":"off","bg_power":"off"}
yeelight-2.0 | 2018-09-10 21:32:18.554 | debug | This id:_yeelight-2.0.ceiling4-Schlafzimmer.control
yeelight-2.0 | 2018-09-10 21:32:18.547 | debug | 192.168.178.41
yeelight-2.0 | 2018-09-10 21:32:18.388 | error | SyntaxError: Unexpected token { in JSON at position 50

`

**Comment by MeisterTR** [comment]
i changed something in error message to see more details, can you install teh version from git and test again?

**Comment by plbartek89** [comment]
`

yeelight-2.0 | 2018-09-11 20:22:26.076 | debug | Error verifying power_on command
-- | -- | -- | --
yeelight-2.0 | 2018-09-11 20:22:26.075 | debug | Wrong respons at power on, ckeck again --> off  <<--soll ist-->> on
yeelight-2.0 | 2018-09-11 20:22:26.054 | error | Error: {"method":"props","params":{"power":"on","main_power":"on"}} {"id":0, "result":["ok"]}
yeelight-2.0 | 2018-09-11 20:22:26.054 | debug | get_prob:_power__192.168.178.41__55443
yeelight-2.0 | 2018-09-11 20:22:26.054 | debug | main_power
yeelight-2.0 | 2018-09-11 20:22:26.054 | debug | power
yeelight-2.0 | 2018-09-11 20:22:26.053 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer","192.168.178.30":"yeelight-2.0.ceiling1-0x0000000004a2035d"}
yeelight-2.0 | 2018-09-11 20:22:26.053 | debug | {"power":"on","main_power":"on"}
yeelight-2.0 | 2018-09-11 20:22:26.053 | debug | This id:_yeelight-2.0.ceiling4-Schlafzimmer.control
yeelight-2.0 | 2018-09-11 20:22:26.045 | debug | 192.168.178.41
yeelight-2.0 | 2018-09-11 20:22:25.986 | debug | Upload State power host: 192.168.178.41 Port: 55443 Value: true
yeelight-2.0 | 2018-09-11 20:22:25.963 | debug | ["yeelight-2","0","ceiling4-Schlafzimmer","control","power"]
yeelight-2.0 | 2018-09-11 20:22:21.651 | debug | Error verifying power_on command
yeelight-2.0 | 2018-09-11 20:22:21.650 | debug | Wrong respons at power on, ckeck again --> on  <<--soll ist-->> off
yeelight-2.0 | 2018-09-11 20:22:21.622 | error | Error: {"method":"props","params":{"power":"off","main_power":"off"}} {"id":0, "result":["ok"]}
yeelight-2.0 | 2018-09-11 20:22:21.622 | debug | get_prob:_power__192.168.178.41__55443
yeelight-2.0 | 2018-09-11 20:22:21.622 | debug | main_power
yeelight-2.0 | 2018-09-11 20:22:21.622 | debug | power
yeelight-2.0 | 2018-09-11 20:22:21.622 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer","192.168.178.30":"yeelight-2.0.ceiling1-0x0000000004a2035d"}
yeelight-2.0 | 2018-09-11 20:22:21.622 | debug | {"power":"off","main_power":"off"}
yeelight-2.0 | 2018-09-11 20:22:21.622 | debug | This id:_yeelight-2.0.ceiling4-Schlafzimmer.control
yeelight-2.0 | 2018-09-11 20:22:21.616 | debug | 192.168.178.41
yeelight-2.0 | 2018-09-11 20:22:21.531 | debug | Upload State power host: 192.168.178.41 Port: 55443 Value: false
yeelight-2.0 | 2018-09-11 20:22:21.498 | debug | ["yeelight-2","0","ceiling4-Schlafzimmer","control","power"]
yeelight-2.0 | 2018-09-11 20:22:09.969 | error | Error: {"method":"props","params":{"power":"on","main_power":"on"}} {"id":0, "result":["ok"]}
yeelight-2.0 | 2018-09-11 20:22:09.969 | debug | main_power
yeelight-2.0 | 2018-09-11 20:22:09.969 | debug | power
yeelight-2.0 | 2018-09-11 20:22:09.969 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer","192.168.178.30":"yeelight-2.0.ceiling1-0x0000000004a2035d"}
yeelight-2.0 | 2018-09-11 20:22:09.969 | debug | {"power":"on","main_power":"on"}
yeelight-2.0 | 2018-09-11 20:22:09.968 | debug | This id:_yeelight-2.0.ceiling4-Schlafzimmer.control
yeelight-2.0 | 2018-09-11 20:22:09.968 | debug | 192.168.178.41
yeelight-2.0 | 2018-09-11 20:22:09.914 | debug | Upload State power host: 192.168.178.41 Port: 55443 Value: true
yeelight-2.0 | 2018-09-11 20:22:09.883 | debug | ["yeelight-2","0","ceiling4-Schlafzimmer","control","power"]
yeelight-2.0 | 2018-09-11 20:22:02.220 | debug | listen to: 192.168.178.30:55443
yeelight-2.0 | 2018-09-11 20:22:02.219 | debug | listen to: 192.168.178.41:55443
yeelight-2.0 | 2018-09-11 20:22:02.219 | debug | sid by socket:_["yeelight-2","0","ceiling1-0x0000000004a2035d","info","IPAdress"]
yeelight-2.0 | 2018-09-11 20:22:02.213 | debug | sid by socket:_["yeelight-2","0","ceiling4-Schlafzimmer","info","IPAdress"]
yeelight-2.0 | 2018-09-11 20:22:02.180 | debug | Update connection for:_yeelight-2.0.ceiling1-0x0000000004a2035d
yeelight-2.0 | 2018-09-11 20:22:02.179 | debug | Update connection for:_yeelight-2.0.ceiling4-Schlafzimmer
yeelight-2.0 | 2018-09-11 20:22:02.067 | debug | regest  params from:yeelight-2.0.ceiling4-Schlafzimmer.control  _params:_["off","52","4415","","1","2","46","","","0","off","off","","50","0","100","16711680","4000"]
yeelight-2.0 | 2018-09-11 20:22:01.979 | debug | Create Device: yeelight-2.0.ceiling4-Schlafzimmer
yeelight-2.0 | 2018-09-11 20:22:01.973 | debug | Create Device: yeelight-2.0.ceiling1-0x0000000004a2035d
yeelight-2.0 | 2018-09-11 20:21:59.970 | debug | der sm:
yeelight-2.0 | 2018-09-11 20:21:59.970 | debug | hier die ate cfg: {"name":"0x0000000004a2035d","ip":"192.168.178.30","port":"55443","smart_name":"","type":"ceiling1"}
yeelight-2.0 | 2018-09-11 20:21:59.970 | debug | der sm:
yeelight-2.0 | 2018-09-11 20:21:59.970 | debug | hier die ate cfg: {"name":"Schlafzimmer","ip":"192.168.178.41","port":"55443","smart_name":"","type":"ceiling4"}
yeelight-2.0 | 2018-09-11 20:21:59.970 | debug | Element:_yeelight-2.0.ceiling1-0x0000000004a2035d
yeelight-2.0 | 2018-09-11 20:21:59.968 | debug | Element:_yeelight-2.0.ceiling4-Schlafzimmer
yeelight-2.0 | 2018-09-11 20:21:59.968 | debug | count Devices:_2
yeelight-2.0 | 2018-09-11 20:21:59.961 | debug | found   Devices:_{"yeelight-2.0.ceiling4-Schlafzimmer":{"type":"device","common":{"name":"ceiling4","icon":"/icons/ceiling4.png"},"native":{"sid":"Schlafzimmer","type":"ceiling4"},"from":"system.adapter
yeelight-2.0 | 2018-09-11 20:21:59.917 | debug | from_conf:   {"devices":[{"name":"0x0000000004a2035d","ip":"192.168.178.30","port":"55443","smart_name":"","type":"ceiling1"},{"name":"Schlafzimmer","ip":"192.168.178.41","port":"55443","smart_name":"",

`

**Comment by MeisterTR** [comment]
that was wat i searched for, please try from git.

**Comment by plbartek89** [comment]
Now , when i switch the light on or off adapter restarts with the following error
`

host.IObroker | 2018-09-12 19:31:40.490 | info | Restart adapter system.adapter.yeelight-2.0 because enabled
-- | -- | -- | --
host.IObroker | 2018-09-12 19:31:40.490 | error | instance system.adapter.yeelight-2.0 terminated with code 0 (OK)
host.IObroker | 2018-09-12 19:31:40.490 | error | Caught by controller[0]:     at TCP.onread (net.js:559:20)
host.IObroker | 2018-09-12 19:31:40.489 | error | Caught by controller[0]:     at Socket.Readable.push (_stream_readable.js:134:10)
host.IObroker | 2018-09-12 19:31:40.489 | error | Caught by controller[0]:     at readableAddChunk (_stream_readable.js:176:18)
host.IObroker | 2018-09-12 19:31:40.489 | error | Caught by controller[0]:     at Socket.emit (events.js:188:7)
host.IObroker | 2018-09-12 19:31:40.489 | error | Caught by controller[0]:     at emitOne (events.js:96:13)
host.IObroker | 2018-09-12 19:31:40.488 | error | Caught by controller[0]:     at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.yeelight-2/lib/yeelight.js:63:5)
host.IObroker | 2018-09-12 19:31:40.488 | error | Caught by controller[0]:     at seperateJSON (/opt/iobroker/node_modules/iobroker.yeelight-2/lib/yeelight.js:226:24)
host.IObroker | 2018-09-12 19:31:40.485 | error | Caught by controller[0]: TypeError: string.replace is not a function
yeelight-2.0 | 2018-09-12 19:31:39.956 | error | TypeError: string.replace is not a function     at seperateJSON (/opt/iobroker/node_modules/iobroker.yeelight-2/lib/yeelight.js:226:24)     at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.y
yeelight-2.0 | 2018-09-12 19:31:39.956 | error | uncaught exception: string.replace is not a function
yeelight-2.0 | 2018-09-12 19:31:39.956 | debug | main_power
yeelight-2.0 | 2018-09-12 19:31:39.956 | debug | power
yeelight-2.0 | 2018-09-12 19:31:39.956 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer"}
yeelight-2.0 | 2018-09-12 19:31:39.956 | debug | {"power":"off","main_power":"off"}
yeelight-2.0 | 2018-09-12 19:31:39.955 | debug | This id:_yeelight-2.0.ceiling4-Schlafzimmer.control
yeelight-2.0 | 2018-09-12 19:31:39.950 | debug | 192.168.178.41
yeelight-2.0 | 2018-09-12 19:31:39.832 | debug | Upload State power host: 192.168.178.41 Port: 55443 Value: false
yeelight-2.0 | 2018-09-12 19:31:39.812 | debug | ["yeelight-2","0","ceiling4-Schlafzimmer","control","power"]
yeelight-2.0 | 2018-09-12 19:31:37.401 | debug | listen to: 192.168.178.41:55443
yeelight-2.0 | 2018-09-12 19:31:37.395 | debug | sid by socket:_["yeelight-2","0","ceiling4-Schlafzimmer","info","IPAdress"]
yeelight-2.0 | 2018-09-12 19:31:37.341 | debug | Update connection for:_yeelight-2.0.ceiling4-Schlafzimmer
yeelight-2.0 | 2018-09-12 19:31:37.340 | debug | regest  params from:yeelight-2.0.ceiling4-Schlafzimmer.control  _params:_["on","73","4415","","1","2","46","","","0","on","off","","50","0","100","16711680","4000"]
yeelight-2.0 | 2018-09-12 19:31:37.207 | debug | Create Device: yeelight-2.0.ceiling4-Schlafzimmer
yeelight-2.0 | 2018-09-12 19:31:35.217 | debug | der sm:
yeelight-2.0 | 2018-09-12 19:31:35.216 | debug | hier die ate cfg: {"name":"Schlafzimmer","ip":"192.168.178.41","port":"55443","smart_name":"","type":"ceiling4"}
yeelight-2.0 | 2018-09-12 19:31:35.201 | debug | Element:_yeelight-2.0.ceiling4-Schlafzimmer
yeelight-2.0 | 2018-09-12 19:31:35.201 | debug | count Devices:_1
yeelight-2.0 | 2018-09-12 19:31:35.195 | debug | found   Devices:_{"yeelight-2.0.ceiling4-Schlafzimmer":{"type":"device","common":{"name":"ceiling4","icon":"/icons/ceiling4.png"},"native":{"sid":"Schlafzimmer","type":"ceiling4"},"from":"system.adapter
yeelight-2.0 | 2018-09-12 19:31:35.171 | debug | from_conf: {"devices":[{"name":"Schlafzimmer","ip":"192.168.178.41","port":"55443","smart_name":"","type":"ceiling4"}]}
yeelight-2.0 | 2018-09-12 19:31:35.171 | info | starting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.yeelight-2, node: v6.14.4
host.IObroker | 2018-09-12 19:31:33.560 | info | instance system.adapter.yeelight-2.0 started with pid 862
host.IObroker | 2018-09-12 19:31:03.525 | info | Restart adapter system.adapter.yeelight-2.0 because enabled
host.IObroker | 2018-09-12 19:31:03.525 | error | instance system.adapter.yeelight-2.0 terminated with code 0 (OK)
Caught | 2018-09-12 19:31:03.525 | error | by controller[0]:     at TCP.onread (net.js:559:20)
Caught | 2018-09-12 19:31:03.524 | error | by controller[0]:     at Socket.Readable.push (_stream_readable.js:134:10)
Caught | 2018-09-12 19:31:03.524 | error | by controller[0]:     at readableAddChunk (_stream_readable.js:176:18)
Caught | 2018-09-12 19:31:03.524 | error | by controller[0]:     at Socket.emit (events.js:188:7)
Caught | 2018-09-12 19:31:03.524 | error | by controller[0]:     at emitOne (events.js:96:13)
Caught | 2018-09-12 19:31:03.524 | error | by controller[0]:     at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.yeelight-2/lib/yeelight.js:63:5)
Caught | 2018-09-12 19:31:03.523 | error | by controller[0]:     at seperateJSON (/opt/iobroker/node_modules/iobroker.yeelight-2/lib/yeelight.js:226:24)
Caught | 2018-09-12 19:31:03.523 | error | by controller[0]: TypeError: string.replace is not a function
yeelight-2.0 | 2018-09-12 19:31:03.503 | info | terminating
yeelight-2.0 | 2018-09-12 19:31:02.992 | error | at TCP.onread (net.js:559:20)
yeelight-2.0 | 2018-09-12 19:31:02.992 | error | at Socket.Readable.push (_stream_readable.js:134:10)
yeelight-2.0 | 2018-09-12 19:31:02.992 | error | at readableAddChunk (_stream_readable.js:176:18)
yeelight-2.0 | 2018-09-12 19:31:02.992 | error | at Socket.emit (events.js:188:7)
yeelight-2.0 | 2018-09-12 19:31:02.992 | error | at emitOne (events.js:96:13)
yeelight-2.0 | 2018-09-12 19:31:02.992 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.yeelight-2/lib/yeelight.js:63:5)
yeelight-2.0 | 2018-09-12 19:31:02.992 | error | at seperateJSON (/opt/iobroker/node_modules/iobroker.yeelight-2/lib/yeelight.js:226:24)
yeelight-2.0 | 2018-09-12 19:31:02.992 | error | TypeError: string.replace is not a function
yeelight-2.0 | 2018-09-12 19:31:02.992 | error | uncaught exception: string.replace is not a function
yeelight-2.0 | 2018-09-12 19:31:02.967 | debug | main_power
yeelight-2.0 | 2018-09-12 19:31:02.961 | debug | power
yeelight-2.0 | 2018-09-12 19:31:02.961 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer"}
yeelight-2.0 | 2018-09-12 19:31:02.960 | debug | {"power":"on","main_power":"on"}
yeelight-2.0 | 2018-09-12 19:31:02.960 | debug | This id:_yeelight-2.0.ceiling4-Schlafzimmer.control
yeelight-2.0 | 2018-09-12 19:31:02.959 | debug | 192.168.178.41
yeelight-2.0 | 2018-09-12 19:31:02.893 | debug | Upload State power host: 192.168.178.41 Port: 55443 Value: true

`

**Comment by MeisterTR** [comment]
please try again from git

**Comment by plbartek89** [comment]
`

yeelight-2.0 | 2018-09-12 21:00:20.016 | debug | Error verifying power_on command
-- | -- | -- | --
yeelight-2.0 | 2018-09-12 21:00:20.015 | debug | Wrong respons at power on, ckeck again --> off  <<--soll ist-->> on
yeelight-2.0 | 2018-09-12 21:00:19.979 | error | Error: could not extract Json from multiple message
yeelight-2.0 | 2018-09-12 21:00:19.979 | debug | get_prob:_power__192.168.178.41__55443
yeelight-2.0 | 2018-09-12 21:00:19.979 | debug | main_power
yeelight-2.0 | 2018-09-12 21:00:19.979 | debug | power
yeelight-2.0 | 2018-09-12 21:00:19.979 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer"}
yeelight-2.0 | 2018-09-12 21:00:19.979 | debug | {"power":"on","main_power":"on"}
yeelight-2.0 | 2018-09-12 21:00:19.978 | debug | This id:_yeelight-2.0.ceiling4-Schlafzimmer.control
yeelight-2.0 | 2018-09-12 21:00:19.978 | debug | 192.168.178.41
yeelight-2.0 | 2018-09-12 21:00:19.928 | debug | Upload State power host: 192.168.178.41 Port: 55443 Value: true
yeelight-2.0 | 2018-09-12 21:00:19.915 | debug | ["yeelight-2","0","ceiling4-Schlafzimmer","control","power"]
yeelight-2.0 | 2018-09-12 21:00:15.921 | debug | Error verifying power_on command
yeelight-2.0 | 2018-09-12 21:00:15.919 | debug | Wrong respons at power on, ckeck again --> on  <<--soll ist-->> off
yeelight-2.0 | 2018-09-12 21:00:15.893 | error | Error: could not extract Json from multiple message
yeelight-2.0 | 2018-09-12 21:00:15.893 | debug | get_prob:_power__192.168.178.41__55443
yeelight-2.0 | 2018-09-12 21:00:15.893 | debug | main_power
yeelight-2.0 | 2018-09-12 21:00:15.893 | debug | power
yeelight-2.0 | 2018-09-12 21:00:15.893 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer"}
yeelight-2.0 | 2018-09-12 21:00:15.893 | debug | {"power":"off","main_power":"off"}
yeelight-2.0 | 2018-09-12 21:00:15.893 | debug | This id:_yeelight-2.0.ceiling4-Schlafzimmer.control
yeelight-2.0 | 2018-09-12 21:00:15.887 | debug | 192.168.178.41
yeelight-2.0 | 2018-09-12 21:00:15.844 | debug | Upload State power host: 192.168.178.41 Port: 55443 Value: false
yeelight-2.0 | 2018-09-12 21:00:15.824 | debug | ["yeelight-2","0","ceiling4-Schlafzimmer","control","power"]

`
Error: could not extract Json from multiple message
But  i can switch off and on now.

**Comment by MeisterTR** [comment]
slowly we come closer... i added some more infos to the error. i think there is a linebreak in the message..

**Comment by plbartek89** [comment]
`

yeelight-2.0 | 2018-09-12 23:00:41.345 | debug | Error verifying power_on command
-- | -- | -- | --
yeelight-2.0 | 2018-09-12 23:00:41.321 | debug | Wrong respons at power on, ckeck again --> on  <<--soll ist-->> off
yeelight-2.0 | 2018-09-12 23:00:41.300 | error | Error:  yeelight.js.seperateJSON: could not extract Json from multiple message_  [{"method":"props","params":{"power":"off","main_power":"off"}} {"id":0, "result":["ok"]} ]
yeelight-2.0 | 2018-09-12 23:00:41.300 | debug | get_prob:_power__192.168.178.41__55443
yeelight-2.0 | 2018-09-12 23:00:41.300 | debug | main_power
yeelight-2.0 | 2018-09-12 23:00:41.300 | debug | power
yeelight-2.0 | 2018-09-12 23:00:41.300 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer"}
yeelight-2.0 | 2018-09-12 23:00:41.300 | debug | {"power":"off","main_power":"off"}
yeelight-2.0 | 2018-09-12 23:00:41.300 | debug | This id:_yeelight-2.0.ceiling4-Schlafzimmer.control
yeelight-2.0 | 2018-09-12 23:00:41.294 | debug | 192.168.178.41
yeelight-2.0 | 2018-09-12 23:00:41.232 | debug | Upload State power host: 192.168.178.41 Port: 55443 Value: false
yeelight-2.0 | 2018-09-12 23:00:41.214 | debug | ["yeelight-2","0","ceiling4-Schlafzimmer","control","power"]
yeelight-2.0 | 2018-09-12 23:00:33.037 | error | Error:  yeelight.js.seperateJSON: could not extract Json from multiple message_  [{"method":"props","params":{"power":"on","main_power":"on"}} {"id":0, "result":["ok"]} ]
yeelight-2.0 | 2018-09-12 23:00:33.037 | debug | main_power
yeelight-2.0 | 2018-09-12 23:00:33.037 | debug | power
yeelight-2.0 | 2018-09-12 23:00:33.037 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer"}
yeelight-2.0 | 2018-09-12 23:00:33.037 | debug | {"power":"on","main_power":"on"}
yeelight-2.0 | 2018-09-12 23:00:33.036 | debug | This id:_yeelight-2.0.ceiling4-Schlafzimmer.control
yeelight-2.0 | 2018-09-12 23:00:33.031 | debug | 192.168.178.41
yeelight-2.0 | 2018-09-12 23:00:32.990 | debug | Upload State power host: 192.168.178.41 Port: 55443 Value: true
yeelight-2.0 | 2018-09-12 23:00:32.961 | debug | ["yeelight-2","0","ceiling4-Schlafzimmer","control","power"]

`

**Comment by MeisterTR** [comment]
so next try..

**Comment by plbartek89** [comment]
`

yeelight-2.0 | 2018-09-13 14:52:36.901 | debug | 192.168.178.41
-- | -- | -- | --
yeelight-2.0 | 2018-09-13 14:52:36.901 | debug | Answer from set_power: ["ok"]
yeelight-2.0 | 2018-09-13 14:52:36.850 | debug | Upload State power host: 192.168.178.41 Port: 55443 Value: false
yeelight-2.0 | 2018-09-13 14:52:36.796 | debug | ["yeelight-2","0","ceiling4-Schlafzimmer","control","power"]
yeelight-2.0 | 2018-09-13 14:52:08.047 | debug | Read bright because poweron: 46
yeelight-2.0 | 2018-09-13 14:52:08.010 | debug | main_power
yeelight-2.0 | 2018-09-13 14:52:08.009 | debug | power
yeelight-2.0 | 2018-09-13 14:52:08.009 | debug | {"192.168.178.41":"yeelight-2.0.ceiling4-Schlafzimmer"}
yeelight-2.0 | 2018-09-13 14:52:08.009 | debug | {"power":"on","main_power":"on"}
yeelight-2.0 | 2018-09-13 14:52:08.008 | debug | This id:_yeelight-2.0.ceiling4-Schlafzimmer.control
yeelight-2.0 | 2018-09-13 14:52:08.008 | debug | 192.168.178.41
yeelight-2.0 | 2018-09-13 14:52:08.004 | debug | get_prob:_bright__192.168.178.41__55443
yeelight-2.0 | 2018-09-13 14:52:07.998 | debug | Answer from set_power: ["ok"]
yeelight-2.0 | 2018-09-13 14:52:07.935 | debug | Upload State power host: 192.168.178.41 Port: 55443 Value: true
yeelight-2.0 | 2018-09-13 14:52:07.914 | debug | ["yeelight-2","0","ceiling4-Schlafzimmer","control","power"]
yeelight-2.0 | 2018-09-13 14:52:00.453 | debug | listen to: 192.168.178.41:55443
yeelight-2.0 | 2018-09-13 14:52:00.449 | debug | sid by socket:_["yeelight-2","0","ceiling4-Schlafzimmer","info","IPAdress"]
yeelight-2.0 | 2018-09-13 14:52:00.337 | debug | regest params from:yeelight-2.0.ceiling4-Schlafzimmer.control  _params:_["off","12","4415","","1","2","46","","","0","off","off","","1","343","100","16711754","4000"]
yeelight-2.0 | 2018-09-13 14:52:00.321 | debug | Update connection for:_yeelight-2.0.ceiling4-Schlafzimmer
yeelight-2.0 | 2018-09-13 14:52:00.287 | debug | Create Device: yeelight-2.0.ceiling4-Schlafzimmer
yeelight-2.0 | 2018-09-13 14:51:58.293 | debug | der sm:
yeelight-2.0 | 2018-09-13 14:51:58.291 | debug | hier die ate cfg: {"name":"Schlafzimmer","ip":"192.168.178.41","port":"55443","smart_name":"","type":"ceiling4"}
yeelight-2.0 | 2018-09-13 14:51:58.268 | debug | Element:_yeelight-2.0.ceiling4-Schlafzimmer
yeelight-2.0 | 2018-09-13 14:51:58.268 | debug | count Devices:_1
yeelight-2.0 | 2018-09-13 14:51:58.267 | debug | found  Devices:_{"yeelight-2.0.ceiling4-Schlafzimmer":{"type":"device","common":{"name":"ceiling4","icon":"/icons/ceiling4.png"},"native":{"sid":"Schlafzimmer","type":"ceiling4"},"from":"system.adapte
yeelight-2.0 | 2018-09-13 14:51:58.213 | debug | from_conf: {"devices":[{"name":"Schlafzimmer","ip":"192.168.178.41","port":"55443","smart_name":"","type":"ceiling4"}]}

`
It looks good no errors , i will test it and report.
Danke.
