### ISSUE TITLE
Support for Bedside Lamp 2?

### ISSUE THREAD

**Issue by 1rfsNet** [iobroker-community-adapters/ioBroker.yeelight-2#73]
Hello, unfortunately I could not find the bslamp 2 in the list. 
Is it not supported atm? My bslamp 1 is working fine.

**Comment by passuff** [comment]
I've trouble to add bedside lamp 2 too. Can't find it with "find" function nor add it manually with ip and port (55443). Any Ideas how to add this lamp?

**Comment by passuff** [comment]
THe model number might be helpful: MJCTD02YL
Portscan just returned port 80. Maybe they closed something?

**Comment by passuff** [comment]
I found it myself. You need to use Yeelight app instead of mihome to activate LAN control- otherwise port 55443 is closed.

**Comment by Diginix** [comment]
This is right. It is the same as for wifi Yeelights. LAN control has to be enabled always once with the Yeelight app.
After that it isn't needed anymore if you have the MiHome app as well.
