### ISSUE TITLE
Control folder does not exist

### ISSUE THREAD

**Issue by huensch112** [iobroker-community-adapters/ioBroker.yeelight-2#83]
Hello,

I have a problem with the current adapter. When I add new lamps, the control folder is missing. Reinstalling Iobroker and the adapter did not bring any improvement. With an existing ioBroker installation where I have already added some lamps, the problem does not exist. If I delete this lamp and add it again, the controls folder is also missing. Can you help me please?
![yeelight](https://user-images.githubusercontent.com/78804254/107374913-6d154700-6ae8-11eb-8e60-51203d7b9813.png)

**Comment by Gerrni** [comment]
I have the same problem. 2 bedside Lamps, the control folder exists only at one lamp. In the Log File I can see this entry

State "yeelight-2.0.Flur_OG.control.power" has no existing object, this might lead to an error in future versions

Reinstall the lamp has no effect.

Adapter version 1.0.3

**Comment by jlssmt** [comment]
The control folder is mostly missing because you have not enabled lan control via yeelight app.
Check this and reply if it helped.

**Comment by Gerrni** [comment]
At the bedside lamp you haven't the option LAN control. What ever... At one I have this folder, at the other one is this missing.
![Screenshot_2021-02-22-23-14-11-69.jpg](https://user-images.githubusercontent.com/40135870/108777349-f7878d00-7563-11eb-93aa-68f3c13f1154.jpg)

![Screenshot_2021-02-22-23-17-02-66_ed98b3aeff8d7dd7fc34fdf3b6f5e30a.jpg](https://user-images.githubusercontent.com/40135870/108777457-1c7c0000-7564-11eb-8b4e-8e8d6d978349.jpg)

![Screenshot_2021-02-22-23-16-53-44_ed98b3aeff8d7dd7fc34fdf3b6f5e30a.jpg](https://user-images.githubusercontent.com/40135870/108777466-1ede5a00-7564-11eb-9011-82125c636f9b.jpg)

**Comment by jlssmt** [comment]
There was "LAN-Control" for sure.
But I have a bedside lamp, too, and it's gone now. Dunno why.

You can see it here:
![image](https://user-images.githubusercontent.com/42897917/109058805-b918dc00-76e3-11eb-8c49-e62f6883f1d2.png)
Source: https://www.china-gadgets.de/xiaomi-mijia-nachttischlampe-2-test/

I'm confused but happy I'm not alone with the problem.
I already asked the Yeelight support (email and facebook) but no response since 7 days.

**Comment by Bluelightcrew** [comment]
I have the same Problem different Lights(Bulb,Strip,ceiling light),all Lan Controls are activated! So Lan Control is not the problem.

**Comment by DirkNeujahr** [comment]
Same here ! After repairing 5 Yeelights 1S (old ones without QR-code and new ones with QR-code printed on) there is a control pojnt but its empty. Still after three days of waiting to initialize theses point there are no entrys under the control datapoint :-(
Are there any alternatives for this adapter ?

**Comment by Gerrni** [comment]
But I have had a notification I Yeelight App for functions with Lan control. But there is no change since last state

**Comment by Carsten0809** [comment]
downgrade the yeelight-app (android)  to V3.2.42 - and then activate LAN CONTROL - worked for me with 2 bulbs

seems that Yeelight removed the option from the app.

**Comment by jlssmt** [comment]
@Carsten0809
> downgrade the yeelight-app (android) to V3.2.42 - and then activate LAN CONTROL - worked for me with 2 bulbs
> 
> seems that Yeelight removed the option from the app.

Yes, this brings back the switch for LAN control. But the switch can't be turned on. 
Neither for Europe, neither for China servers.
My apk is from apkmirror.com if that matters...

**Comment by Gerrni** [comment]
It works with the version below!

[Screenshot_2021-05-21-07-39-26-62_ed98b3aeff8d7dd7fc34fdf3b6f5e30a.jpg](https://user-images.githubusercontent.com/40135870/119087679-d2da6e80-ba07-11eb-85f4-d8b310b86f2a.jpg)

![Screenshot_2021-05-21-07-39-40-90_ed98b3aeff8d7dd7fc34fdf3b6f5e30a.jpg](https://user-images.githubusercontent.com/40135870/119087704-db32a980-ba07-11eb-9b06-907b18b7e1c7.jpg)

![Screenshot_2021-05-21-07-41-01-94_ed98b3aeff8d7dd7fc34fdf3b6f5e30a.jpg](https://user-images.githubusercontent.com/40135870/119087754-eb4a8900-ba07-11eb-9624-a0b3c47ad2dc.jpg)

**Comment by jlssmt** [comment]
@Gerrni 
> It works with the version below!

I can't switch the slider, no matter if I'm on yeelight apk 3.2.40 or 3.2.42
On which firmware version is your xiaomi (!) bedside lamp?
Do you have xiaomi (!) bedside lamp v1 or v2?
There is also a bslamp2 from yeelight instead of xiaomi. 

I have xiaomi bslamp2 and fw 2.0.6_0041

**Comment by Gerrni** [comment]
Hi,

i have this one:
 [https://www.amazon.de/Xiaomi-Nachttisch-Ambientelampe-Appverbindung-Sprachassistenten/dp/B07SPH2Y3X/ref=asc_df_B07SPH2Y3X/?tag=googshopde-21&linkCode=df0&hvadid=379194608068&hvpos=&hvnetw=g&hvrand=11689185572133120213&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9043746&hvtargid=pla-803035283494&psc=1&th=1&psc=1&tag=&ref=&adgrpid=78053283795&hvpone=&hvptwo=&hvadid=379194608068&hvpos=&hvnetw=g&hvrand=11689185572133120213&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9043746&hvtargid=pla-803035283494](url)

Firmware Version: 2.0.6_0030

**Comment by jlssmt** [comment]
@Gerrni 
> Hi,
> 
> i have this one:
> 
> Firmware Version: 2.0.6_0030

Yep, that's also my model. So make sure not to upgrade your firmware to 2.0.6_0041. Otherwise you won't be able to turn LAN control on anymore.

This issue is related to Yeelight/Xiaomi and not this adapter.
You can read the issue here:
https://forum.yeelight.com/t/topic/22664

And the only possible fix I found is here (custom firmware flash):
https://community.home-assistant.io/t/custom-firmware-esphome-xiaomi-bslamp2/284406

**Comment by Gerrni** [comment]
You are right; i have another lamp from the same modell. But with Firmware 2.0.6_0041. There i can see the LAN Control Button but can´t switch to "on".
