### ISSUE TITLE
pendant "main_power" without function

### ISSUE THREAD

**Issue by jlssmt** [iobroker-community-adapters/ioBroker.yeelight-2#85]
Hello,

the pendant ceiling lamp has the object "main_power". However, this has no function. "power" and "bg_power" works.
Without "main_power" it is not possible to switch off the main light separately from the ambient lighting.

![image](https://user-images.githubusercontent.com/42897917/108625431-3675ef80-744b-11eb-9fe0-071c52822bcd.png)

**Comment by canim60** [comment]
i have this problem too
