### ISSUE TITLE
add yltd003 screenbar

### ISSUE THREAD

**Issue by nob0dy80** [iobroker-community-adapters/ioBroker.yeelight-2#86]
Well, this adapter isnt updated for a year so i dont have much hope to get this fully included to my iobroker enviroment.

screenbar got full chroma leds on its back and white leds in front (color temperature is adjustable).

front leds are controlable (with some errors), chroma leds on its back not in any kind. effects are working too.

**Comment by 1rfsNet** [comment]
This is working fine for me. I just added the lamp in Yeelight app, used the find button and set it as desklamp. I can fully control the backlight (color, etc.)
