### ISSUE TITLE
Bulk RGB automatic power on after refresh the VIS-View

### ISSUE THREAD

**Issue by KL-AU-S** [iobroker-community-adapters/ioBroker.yeelight-2#9]
My RGB-Lamp named Pilz will power on after i refresh my VIS-View. All other yeelight-lamp´s stayed turned off it´s only happen on the bulk-rgb. Here the debug log during refresh of the vis-view:

yeelight-2.0 | 2018-09-21 07:37:35.084 | debug | power
-- | -- | -- | --
yeelight-2.0 | 2018-09-21 07:37:35.084 | debug | {"192.168.0.197":"yeelight-2.0.stripe-Stripe1","192.168.0.196":"yeelight-2.0.ceiling1-Badezimmerlampe","192.168.0.198":"yeelight-2.0.ceiling1-Kuechenlampe","192.168.0.195":"yeelight-2.0.color-Pilz"}
yeelight-2.0 | 2018-09-21 07:37:35.084 | debug | {"power":"on"}
yeelight-2.0 | 2018-09-21 07:37:35.084 | debug | This id:_yeelight-2.0.color-Pilz.control
yeelight-2.0 | 2018-09-21 07:37:35.084 | debug | 192.168.0.195
yeelight-2.0 | 2018-09-21 07:37:33.930 | debug | Answer from rgb _power on an color mode before set: ["ok"]
yeelight-2.0 | 2018-09-21 07:37:33.896 | debug | rgb to hs: [240,43]
yeelight-2.0 | 2018-09-21 07:37:33.896 | debug | Upload State rgb host: 192.168.0.195 Port: 55443 Value: #141432
yeelight-2.0 | 2018-09-21 07:37:33.889 | debug | ["yeelight-2","0","color-Pilz","control","rgb"]

Kind regards klaus

**Comment by MeisterTR** [comment]
Witch widget do you use in your view?

**Comment by KL-AU-S** [comment]
Error occour because the value-rgb was set to #141432. 
KInd regards
klaus

**Comment by KL-AU-S** [comment]
Error occour because the value-rgb was set to #141432. 
KInd regards
klaus

**Comment by KL-AU-S** [comment]
I tested again and in fact the light will be powered on when any color is defined in the rgb field and the vis
view is refreshed. Also the light is powered on when i define a color in the rgb field and when i restart the adapter.
Logfile:

yeelight-2.0 | 2018-09-22 08:26:33.700 | debug | power
-- | -- | -- | --
yeelight-2.0 | 2018-09-22 08:26:33.700 | debug | {"192.168.0.197":"yeelight-2.0.stripe-Stripe1","192.168.0.196":"yeelight-2.0.ceiling1-Badezimmerlampe","192.168.0.198":"yeelight-2.0.ceiling1-Kuechenlampe","192.168.0.195":"yeelight-2.0.color-Pilz"}
yeelight-2.0 | 2018-09-22 08:26:33.700 | debug | {"power":"off"}
yeelight-2.0 | 2018-09-22 08:26:33.700 | debug | This id:_yeelight-2.0.color-Pilz.control
yeelight-2.0 | 2018-09-22 08:26:33.700 | debug | 192.168.0.195
yeelight-2.0 | 2018-09-22 08:26:32.278 | debug | Answer from set_power: ["ok"]
yeelight-2.0 | 2018-09-22 08:26:32.262 | debug | Upload State power host: 192.168.0.195 Port: 55443 Value: false
yeelight-2.0 | 2018-09-22 08:26:32.262 | debug | ["yeelight-2","0","color-Pilz","control","power"]
yeelight-2.0 | 2018-09-22 08:26:24.041 | error | Error: connect ETIMEDOUT 192.168.0.197:55443
yeelight-2.0 | 2018-09-22 08:26:24.041 | error | Error: connect ETIMEDOUT 192.168.0.197:55443
yeelight-2.0 | 2018-09-22 08:26:24.010 | error | Error: connect ETIMEDOUT 192.168.0.197:55443
yeelight-2.0 | 2018-09-22 08:26:24.010 | debug | regest params from:yeelight-2.0.stripe-Stripe1.control _params:_undefined
yeelight-2.0 | 2018-09-22 08:26:03.034 | debug | regest  params from:yeelight-2.0.ceiling1-Kuechenlampe.control  _params:_["off","1","4000","","0","2","1","","","0","","","","","","","",""]
yeelight-2.0 | 2018-09-22 08:26:03.034 | debug | regest  params from:yeelight-2.0.color-Pilz.control  _params:_["on","","3000","8289918","","1","50","240","100","0","","","","","","","",""]
yeelight-2.0 | 2018-09-22 08:26:03.019 | debug | listen to: 192.168.0.195:55443
yeelight-2.0 | 2018-09-22 08:26:03.019 | debug | listen to: 192.168.0.198:55443
yeelight-2.0 | 2018-09-22 08:26:03.019 | debug | listen to: 192.168.0.196:55443
yeelight-2.0 | 2018-09-22 08:26:03.019 | debug | listen to: 192.168.0.197:55443
yeelight-2.0 | 2018-09-22 08:26:03.019 | debug | regest  params from:yeelight-2.0.ceiling1-Badezimmerlampe.control  _params:_["off","100","4000","","0","2","100","","","0","","","","","","","",""]
yeelight-2.0 | 2018-09-22 08:26:03.019 | debug | Update connection for:_yeelight-2.0.color-Pilz
yeelight-2.0 | 2018-09-22 08:26:03.019 | debug | Update connection for:_yeelight-2.0.ceiling1-Kuechenlampe
yeelight-2.0 | 2018-09-22 08:26:03.019 | debug | Update connection for:_yeelight-2.0.ceiling1-Badezimmerlampe
yeelight-2.0 | 2018-09-22 08:26:03.019 | debug | Update connection for:_yeelight-2.0.stripe-Stripe1
yeelight-2.0 | 2018-09-22 08:26:03.003 | debug | sid by socket:_["yeelight-2","0","color-Pilz","info","IPAdress"]
yeelight-2.0 | 2018-09-22 08:26:03.003 | debug | sid by socket:_["yeelight-2","0","ceiling1-Kuechenlampe","info","IPAdress"]
yeelight-2.0 | 2018-09-22 08:26:03.003 | debug | sid by socket:_["yeelight-2","0","ceiling1-Badezimmerlampe","info","IPAdress"]
yeelight-2.0 | 2018-09-22 08:26:03.003 | debug | sid by socket:_["yeelight-2","0","stripe-Stripe1","info","IPAdress"]
yeelight-2.0 | 2018-09-22 08:26:02.987 | debug | Create Device: yeelight-2.0.color-Pilz
yeelight-2.0 | 2018-09-22 08:26:02.987 | debug | Create Device: yeelight-2.0.ceiling1-Kuechenlampe
yeelight-2.0 | 2018-09-22 08:26:02.987 | debug | Create Device: yeelight-2.0.stripe-Stripe1
yeelight-2.0 | 2018-09-22 08:26:02.987 | debug | Create Device: yeelight-2.0.ceiling1-Badezimmerlampe
yeelight-2.0 | 2018-09-22 08:26:02.612 | debug | system.adapter.admin.0: logging true
yeelight-2.0 | 2018-09-22 08:26:00.972 | debug | der sm: Pilz
yeelight-2.0 | 2018-09-22 08:26:00.972 | debug | hier die ate cfg: {"name":"Pilz","ip":"192.168.0.195","port":"55443","smart_name":"Pilz","type":"color"}
yeelight-2.0 | 2018-09-22 08:26:00.972 | debug | der sm: Kuechenlampe
yeelight-2.0 | 2018-09-22 08:26:00.972 | debug | hier die ate cfg: {"name":"Kuechenlampe","ip":"192.168.0.198","port":"55443","smart_name":"Kuechenlampe","type":"ceiling1"}
yeelight-2.0 | 2018-09-22 08:26:00.972 | debug | der sm: Badezimmerlampe
yeelight-2.0 | 2018-09-22 08:26:00.972 | debug | hier die ate cfg:  {"name":"Badezimmerlampe","ip":"192.168.0.196","port":"55443","smart_name":"Badezimmerlampe","type":"ceiling1"}
yeelight-2.0 | 2018-09-22 08:26:00.972 | debug | der sm: Stripe1
yeelight-2.0 | 2018-09-22 08:26:00.972 | debug | hier die ate cfg: {"name":"Stripe1","ip":"192.168.0.197","port":"55443","smart_name":"Stripe1","type":"stripe"}
yeelight-2.0 | 2018-09-22 08:26:00.972 | debug | Element:_yeelight-2.0.color-Pilz
yeelight-2.0 | 2018-09-22 08:26:00.972 | debug | Element:_yeelight-2.0.ceiling1-Kuechenlampe
yeelight-2.0 | 2018-09-22 08:26:00.972 | debug | Element:_yeelight-2.0.ceiling1-Badezimmerlampe
yeelight-2.0 | 2018-09-22 08:26:00.972 | debug | Element:_yeelight-2.0.stripe-Stripe1
yeelight-2.0 | 2018-09-22 08:26:00.972 | debug | count Devices:_4
yeelight-2.0 | 2018-09-22 08:26:00.972 | debug | found  Devices:_{"yeelight-2.0.stripe-Stripe1":{"type":"device","common":{"name":"stripe","icon":"/icons/stripe.png"},"native":{"sid":"Stripe1","type":"stripe"},"from":"system.adapter.yeelight-2.0","u
yeelight-2.0 | 2018-09-22 08:26:00.956 | debug | from_conf:  {"devices":[{"name":"Badezimmerlampe","ip":"192.168.0.196","port":"55443","smart_name":"Badezimmerlampe","type":"ceiling1"},{"name":"Stripe1","ip":"192.168.0.197","port":"55443","smart_nam
yeelight-2.0 | 2018-09-22 08:26:00.956 | info | starting. Version 0.4.0 in C:/ioBroker/node_modules/iobroker.yeelight-2, node: v10.5.0
yeelight-2.0 | 2018-09-22 08:26:00.847 | debug | statesDB connected
yeelight-2.0 | 2018-09-22 08:26:00.831 | debug | objectDB connected

**Comment by MeisterTR** [comment]
should be fixed in #14
